allocate_tdsops – x3d2
allocate_tdsops Subroutine
32 statements
Source File
public subroutine allocate_tdsops(dirps, backend, mesh, der1st_scheme, der2nd_scheme, interpl_scheme, stagder_scheme)
Arguments
Type Intent Optional Attributes Name
type(dirps_t), intent(inout) :: dirps
class(base_backend_t), intent(in) :: backend
type(mesh_t), intent(in) :: mesh
character(len=*), intent(in) :: der1st_scheme
character(len=*), intent(in) :: der2nd_scheme
character(len=*), intent(in) :: interpl_scheme
character(len=*), intent(in) :: stagder_scheme
Calls
Called by
Call graph
allocate_tdsops calls alloc_tdsops, get_n
get_n_phi calls get_n
init calls allocate_tdsops
solver_t calls init
case_init calls init
case_channel_init calls case_init
case_cylinder_init calls case_init
case_generic_init calls case_init
case_tgv_init calls case_init
case_channel_t calls case_channel_init
case_cylinder_t calls case_cylinder_init
case_generic_t calls case_generic_init
case_tgv_t calls case_tgv_init