apply_outflow_bc_cylinder – x3d2
apply_outflow_bc_cylinder Subroutine
20 statements
Source File
public subroutine apply_outflow_bc_cylinder(self, u, v, w)
Type Bound
case_cylinder_t
Arguments
Type Intent Optional Attributes Name
class(case_cylinder_t) :: self
class(field_t), intent(inout) :: u
class(field_t), intent(inout) :: v
class(field_t), intent(inout) :: w
Calls
Called by
Call graph
apply_outflow_bc_cylinder calls field_set_face, compute_outflow_params
compute_outflow_params calls mpi_allreduce, get_dims, slice_max_sum
get_dims calls get_dims_dataloc
boundary_conditions_cylinder calls apply_outflow_bc_cylinder
pre_correction_cylinder calls apply_outflow_bc_cylinder