base_init – x3d2
base_init Subroutine
69 statements
Source File
public subroutine base_init(self, mesh, xdirps, ydirps, zdirps, n_spec, n_sp_st)
Type Bound
poisson_fft_t
Arguments
Type Intent Optional Attributes Name
class(poisson_fft_t) :: self
type(mesh_t), intent(in), target :: mesh
type(dirps_t), intent(in) :: xdirps
type(dirps_t), intent(in) :: ydirps
type(dirps_t), intent(in) :: zdirps
integer, intent(in), dimension(3) :: n_spec
integer, intent(in), dimension(3) :: n_sp_st
Calls
Call graph
base_init calls get_dims, get_global_dims, stretching_matrix, waves_set
get_dims calls get_dims_dataloc
get_global_dims calls get_dims_dataloc
stretching_matrix calls get_imag, get_km, get_km_im, get_km_re, get_real
waves_set calls wave_numbers
get_km calls get_imag, get_real
get_km_im calls get_imag, get_km
get_km_re calls get_km, get_real