boundary_conditions_channel – x3d2
boundary_conditions_channel Subroutine
11 statements
Source File
public subroutine boundary_conditions_channel(self)
Type Bound
case_channel_t
Arguments
Type Intent Optional Attributes Name
class(case_channel_t) :: self
Calls
Call graph
boundary_conditions_channel calls field_shift, field_volume_integral, mpi_allreduce, get_global_dims
get_global_dims calls get_dims_dataloc