case_finalise – x3d2
case_finalise Subroutine
5 statements
Source File
public subroutine case_finalise(self)
Type Bound
base_case_t
Arguments
Type Intent Optional Attributes Name
class(base_case_t) :: self
Calls
Called by
Call graph
case_finalise calls finalise, is_root
run calls case_finalise
xcompact calls run