case_init – x3d2
case_init Subroutine
14 statements
Source File
public subroutine case_init(self, backend, mesh, host_allocator)
Type Bound
base_case_t
Arguments
Type Intent Optional Attributes Name
class(base_case_t) :: self
class(base_backend_t), intent(inout), target :: backend
type(mesh_t), intent(inout), target :: mesh
type(allocator_t), intent(inout), target :: host_allocator
Calls
Called by
Call graph
case_init calls initial_conditions, handle_restart, is_restart, init
init calls init_poisson_fft, allocate_tdsops, get_argument, get_block, get_global_dims, is_root
allocate_tdsops calls alloc_tdsops, get_n
get_block calls get_padded_dims, create_block, set_shape
get_global_dims calls get_dims_dataloc
get_dims calls get_dims_dataloc
set_field_data calls get_block, release_block, copy_data_to_f, get_rdr_from_dirs, reorder
get_n_phi calls get_n
get_padded_dims_dir calls get_n_groups
get_padded_dims_phi calls get_padded_dims
get_n_groups_phi calls get_n_groups
case_channel_init calls case_init
case_generic_init calls case_init
case_tgv_init calls case_init
case_channel_t calls case_channel_init
case_generic_t calls case_generic_init
case_tgv_t calls case_tgv_init