cleanup_field_buffers – x3d2
cleanup_field_buffers Subroutine
12 statements
Source File
public subroutine cleanup_field_buffers(field_buffers)
Arguments
Type Intent Optional Attributes Name
type(field_buffer_map_t), intent(inout), allocatable :: field_buffers(:)
Called by
Call graph
case_finalise calls finalise
run calls handle_io_step, case_finalise
xcompact calls run