cleanup_field_arrays – x3d2
cleanup_field_arrays Subroutine
15 statements
Source File
public subroutine cleanup_field_arrays(solver, field_ptrs, host_fields)
Arguments
Type Intent Optional Attributes Name
class(solver_t), intent(in) :: solver
type(field_ptr_t), intent(inout), allocatable :: field_ptrs(:)
type(field_ptr_t), intent(inout), allocatable :: host_fields(:)
Calls
Called by
Call graph
cleanup_field_arrays calls release_block
run calls handle_io_step
xcompact calls run