compute_pressure_vert – x3d2
compute_pressure_vert Subroutine
12 statements
Source File
public subroutine compute_pressure_vert(solver)
Interpolates the pressure field from CELL (DIR_Z) to VERT (DIR_X) for snapshot output and rescales from pseudo-pressure to physical (kinematic) pressure.
Arguments
Type Intent Optional Attributes Name
class(solver_t), intent(inout) :: solver
Calls
Called by
Call graph
compute_pressure_vert calls get_block, interpl_c2v, vecadd
get_block calls create_block, set_shape
interpl_c2v calls get_block, release_block, reorder, tds_solve
run calls compute_pressure_vert
xcompact calls run