compute_rank_pos_from_global – x3d2
compute_rank_pos_from_global Subroutine
17 statements
Source File
public pure subroutine compute_rank_pos_from_global(self, global_ranks)
From the global rank maps, fills in the rank position as well as the previous and next rank in the par structure
Type Bound
par_t
Arguments
Type Intent Optional Attributes Name
class(par_t), intent(inout) :: self
integer, intent(in), dimension(:, :, :) :: global_ranks
Called by
Call graph
decomposition_2decomp calls compute_rank_pos_from_global
decomposition_generic calls compute_rank_pos_from_global
mesh_init calls decomposition_2decomp, decomposition_generic
mesh_t calls mesh_init