compute_outflow_params – x3d2
compute_outflow_params Subroutine
27 statements
Source File
public subroutine compute_outflow_params(self, out_vel, flow_rate_diff)
Type Bound
case_cylinder_t
Arguments
Type Intent Optional Attributes Name
class(case_cylinder_t) :: self
real(kind=dp), intent(out) :: out_vel
real(kind=dp), intent(out) :: flow_rate_diff
Calls
Called by
Call graph
compute_outflow_params calls mpi_allreduce, get_dims, slice_max_sum
get_dims calls get_dims_dataloc
define_bc_cylinder calls compute_outflow_params