compute_derived_fields – x3d2
compute_derived_fields Subroutine
78 statements
Source File
public subroutine compute_derived_fields(solver, output_vorticity, output_qcriterion)
Compute derived fields from the velocity gradient tensor.
All 9 components of the velocity gradient tensor are computed once, then used to evaluate whichever quantities are enabled (vorticity magnitude, Q-criterion).
Arguments
Type Intent Optional Attributes Name
class(solver_t), intent(inout) :: solver
logical, intent(in) :: output_vorticity
logical, intent(in) :: output_qcriterion
Calls
Called by
Call graph
compute_derived_fields calls get_block, release_block, reorder, tds_solve
get_block calls create_block, set_shape
run calls compute_derived_fields
xcompact calls run