copy_into_buffers – x3d2
copy_into_buffers Subroutine
17 statements
Source File
public subroutine copy_into_buffers(u_send_s, u_send_e, u, n, n_groups)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(out), dimension(:, :, :) :: u_send_s
real(kind=dp), intent(out), dimension(:, :, :) :: u_send_e
real(kind=dp), intent(in), dimension(:, :, :) :: u
integer, intent(in) :: n
integer, intent(in) :: n_groups
Called by
Call graph
tds_solve_dist calls copy_into_buffers
transeq_omp_dist calls copy_into_buffers
transeq_species_omp calls copy_into_buffers
tds_solve_omp calls tds_solve_dist
transeq_x_omp calls transeq_omp_dist
transeq_y_omp calls transeq_omp_dist
transeq_z_omp calls transeq_omp_dist