create_block – x3d2
create_block Function
15 statements
Source File
public function create_block(self, next) result(ptr)
Allocate memory for a new block and return a pointer to a new m_allocator object.
Type Bound
allocator_t
Arguments
Type Intent Optional Attributes Name
class(allocator_t), intent(inout) :: self
class(field_t), intent(in), pointer :: next
Return Value class(field_t), pointer
Called by
Call graph
get_block calls create_block
compute_derived_fields calls get_block
compute_pressure_vert calls get_block, interpl_c2v
curl calls get_block, curl
divergence_v2c calls get_block
get_field_data calls get_block
gradient_c2v calls get_block
initial_conditions_channel calls get_block, set_field_data
initial_conditions_cylinder calls get_block, set_field_data
init calls get_block
interpl_c2v calls get_block
laplacian calls get_block
poisson_fft calls get_block
pressure_correction calls get_block, divergence_v2p, gradient_p2v
print_div_max_mean calls get_block, divergence_v2p
print_enstrophy calls get_block, curl
reorder_cuda calls get_block
run calls get_block, compute_derived_fields, compute_pressure_vert, pressure_correction, update_stats, handle_io_step
scalar_product_omp calls get_block, get_field_data
set_field_data calls get_block
set_init calls get_block, set_field_data
setup_field_arrays calls get_block, get_field_data
transeq_cuda_dist calls get_block
transeq_default calls get_block, transeq_species
transeq_lowmem calls get_block, transeq_species
transeq_omp_dist calls get_block
transeq_species calls get_block
transeq_species_cuda calls get_block
transeq_species_omp calls get_block
solver_t calls init
time_intg_t calls init
case_init calls init, handle_restart
divergence_v2p calls divergence_v2c
gradient_p2v calls gradient_c2v
initial_conditions_tgv calls set_init
postprocess_channel calls print_div_max_mean, print_enstrophy
postprocess_cylinder calls print_div_max_mean, print_enstrophy
postprocess_generic calls print_div_max_mean, print_enstrophy
postprocess_tgv calls print_div_max_mean, print_enstrophy
transeq_x_cuda calls transeq_cuda_dist
transeq_x_omp calls transeq_omp_dist
transeq_y_cuda calls transeq_cuda_dist
transeq_y_omp calls transeq_omp_dist
transeq_z_cuda calls transeq_cuda_dist
transeq_z_omp calls transeq_omp_dist
xcompact calls run
case_channel_init calls case_init
case_cylinder_init calls case_init
case_generic_init calls case_init
case_tgv_init calls case_init
case_channel_t calls case_channel_init
case_cylinder_t calls case_cylinder_init
case_generic_t calls case_generic_init
case_tgv_t calls case_tgv_init