curl – x3d2
curl Subroutine
7 statements
Source File
public subroutine curl(self, o_i_hat, o_j_hat, o_k_hat, u, v, w)
Wrapper for curl
Type Bound
solver_t
Arguments
Type Intent Optional Attributes Name
class(solver_t) :: self
class(field_t), intent(inout) :: o_i_hat
Vector components of the output vector field Omega
class(field_t), intent(inout) :: o_j_hat
Vector components of the output vector field Omega
class(field_t), intent(inout) :: o_k_hat
Vector components of the output vector field Omega
class(field_t), intent(in) :: u
class(field_t), intent(in) :: v
class(field_t), intent(in) :: w
Calls
Called by
Call graph
curl calls curl, get_block, release_block, reorder, tds_solve, vecadd
get_block calls create_block, set_shape
print_enstrophy calls curl
postprocess_channel calls print_enstrophy
postprocess_cylinder calls print_enstrophy
postprocess_generic calls print_enstrophy
postprocess_tgv calls print_enstrophy