curl – x3d2
curl Subroutine
50 statements
Source File
public subroutine curl(self, o_i_hat, o_j_hat, o_k_hat, u, v, w, x_der1st, y_der1st, z_der1st)
Curl of a vector field (u, v, w).
Evaluated at the data_loc defined by u, v, w fields.
All the input and output fields are in DIR_X layout.
Type Bound
vector_calculus_t
Arguments
Type Intent Optional Attributes Name
class(vector_calculus_t) :: self
class(field_t), intent(inout) :: o_i_hat
Vector components of the output vector field Omega
class(field_t), intent(inout) :: o_j_hat
Vector components of the output vector field Omega
class(field_t), intent(inout) :: o_k_hat
Vector components of the output vector field Omega
class(field_t), intent(in) :: u
class(field_t), intent(in) :: v
class(field_t), intent(in) :: w
class(tdsops_t), intent(in) :: x_der1st
class(tdsops_t), intent(in) :: y_der1st
class(tdsops_t), intent(in) :: z_der1st
Calls
Called by
Call graph
curl calls get_block, release_block, reorder, tds_solve, vecadd, curl
get_block calls get_padded_dims, create_block, set_shape
get_padded_dims_dir calls get_n_groups
get_padded_dims_phi calls get_padded_dims
get_n_groups_phi calls get_n_groups
print_enstrophy calls curl
postprocess_channel calls print_enstrophy
postprocess_generic calls print_enstrophy
postprocess_tgv calls print_enstrophy