decomposition_2decomp – x3d2
decomposition_2decomp Subroutine
42 statements
Source File
public subroutine decomposition_2decomp(grid, par)
Uses
m_mesh_content
decomp_2d
decomp_2d_mpi
Performs 2D mesh decomposition using 2decomp&fft
Arguments
Type Intent Optional Attributes Name
class(grid_t), intent(inout) :: grid
class(par_t), intent(inout) :: par
Calls
Called by
Call graph
decomposition_2decomp calls decomp_2d_init, mpi_allreduce, mpi_cart_coords, mpi_comm_rank, compute_rank_pos_from_global, copy_vert2cell_dims, is_root, xsize, xstart
mesh_init calls decomposition_2decomp
mesh_t calls mesh_init