decomposition_generic – x3d2
decomposition_generic Subroutine
19 statements
Source File
public subroutine decomposition_generic(grid, par)
Uses
m_mesh_content
Arguments
Type Intent Optional Attributes Name
class(grid_t), intent(inout) :: grid
class(par_t), intent(inout) :: par
Calls
Called by
Call graph
decomposition_generic calls compute_rank_pos_from_global, copy_vert2cell_dims, is_root
mesh_init calls decomposition_generic
mesh_t calls mesh_init