define_BC_cylinder – x3d2
define_BC_cylinder Subroutine
39 statements
Source File
public subroutine define_BC_cylinder(self)
Type Bound
case_cylinder_t
Arguments
Type Intent Optional Attributes Name
class(case_cylinder_t) :: self
Calls
Call graph
define_bc_cylinder calls compute_outflow_params, get_block, get_dims, release_block, set_data_loc, set_field_data
compute_outflow_params calls get_dims, mpi_allreduce, slice_max_sum
get_block calls create_block, set_shape
get_dims calls get_dims_dataloc
set_field_data calls get_block, release_block, copy_data_to_f, get_rdr_from_dirs, reorder