define_BC_channel – x3d2
define_BC_channel Subroutine
49 statements
Source File
public subroutine define_BC_channel(self)
Type Bound
case_channel_t
Arguments
Type Intent Optional Attributes Name
class(case_channel_t) :: self
Calls
Call graph
define_bc_channel calls field_shift, field_volume_integral, mpi_allreduce, get_block, get_dims, get_global_dims, release_block, set_data_loc, set_field_data
get_block calls create_block, set_shape
get_dims calls get_dims_dataloc
get_global_dims calls get_dims_dataloc
set_field_data calls get_block, release_block, copy_data_to_f, get_rdr_from_dirs, reorder