der_univ_dist – x3d2
der_univ_dist Subroutine
64 statements
Source File
public subroutine der_univ_dist(du, send_u_s, send_u_e, u, u_s, u_e, n_tds, n_rhs, coeffs_s, coeffs_e, coeffs, ffr, fbc, faf)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(out), dimension(:, :) :: du
real(kind=dp), intent(out), dimension(:, :) :: send_u_s
real(kind=dp), intent(out), dimension(:, :) :: send_u_e
real(kind=dp), intent(in), dimension(:, :) :: u
real(kind=dp), intent(in), dimension(:, :) :: u_s
real(kind=dp), intent(in), dimension(:, :) :: u_e
integer, intent(in) :: n_tds
integer, intent(in) :: n_rhs
real(kind=dp), intent(in), dimension(:, :) :: coeffs_s
real(kind=dp), intent(in), dimension(:, :) :: coeffs_e
real(kind=dp), intent(in), dimension(:) :: coeffs
real(kind=dp), intent(in), dimension(:) :: ffr
real(kind=dp), intent(in), dimension(:) :: fbc
real(kind=dp), intent(in), dimension(:) :: faf
Called by
Call graph
exec_dist_tds_compact calls der_univ_dist
exec_dist_transeq_compact calls der_univ_dist
tds_solve_dist calls exec_dist_tds_compact
transeq_omp_dist calls exec_dist_transeq_compact
transeq_species_omp calls exec_dist_transeq_compact
tds_solve_omp calls tds_solve_dist
transeq_x_omp calls transeq_omp_dist
transeq_y_omp calls transeq_omp_dist
transeq_z_omp calls transeq_omp_dist