der_univ_fused_subs – x3d2
der_univ_fused_subs Subroutine
57 statements
Source File
public subroutine der_univ_fused_subs(rhs_du, dud, d2u, v, du_recv_s, du_recv_e, dud_recv_s, dud_recv_e, d2u_recv_s, d2u_recv_e, nu, n, du_dist_sa, du_dist_sc, du_strch, dud_dist_sa, dud_dist_sc, dud_strch, d2u_dist_sa, d2u_dist_sc, d2u_strch, d2u_strch_cor)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(inout), dimension(:, :) :: rhs_du
real(kind=dp), intent(in), dimension(:, :) :: dud
real(kind=dp), intent(in), dimension(:, :) :: d2u
real(kind=dp), intent(in), dimension(:, :) :: v
real(kind=dp), intent(in), dimension(:, :) :: du_recv_s
real(kind=dp), intent(in), dimension(:, :) :: du_recv_e
real(kind=dp), intent(in), dimension(:, :) :: dud_recv_s
real(kind=dp), intent(in), dimension(:, :) :: dud_recv_e
real(kind=dp), intent(in), dimension(:, :) :: d2u_recv_s
real(kind=dp), intent(in), dimension(:, :) :: d2u_recv_e
real(kind=dp), intent(in) :: nu
integer, intent(in) :: n
real(kind=dp), intent(in), dimension(:) :: du_dist_sa
real(kind=dp), intent(in), dimension(:) :: du_dist_sc
real(kind=dp), intent(in), dimension(:) :: du_strch
real(kind=dp), intent(in), dimension(:) :: dud_dist_sa
real(kind=dp), intent(in), dimension(:) :: dud_dist_sc
real(kind=dp), intent(in), dimension(:) :: dud_strch
real(kind=dp), intent(in), dimension(:) :: d2u_dist_sa
real(kind=dp), intent(in), dimension(:) :: d2u_dist_sc
real(kind=dp), intent(in), dimension(:) :: d2u_strch
real(kind=dp), intent(in), dimension(:) :: d2u_strch_cor
Called by
Call graph
exec_dist_transeq_compact calls der_univ_fused_subs
transeq_omp_dist calls exec_dist_transeq_compact
transeq_species_omp calls exec_dist_transeq_compact
transeq_x_omp calls transeq_omp_dist
transeq_y_omp calls transeq_omp_dist
transeq_z_omp calls transeq_omp_dist