der_univ_dist – x3d2
der_univ_dist Subroutine
55 statements
Source File
public subroutine der_univ_dist(du, send_u_s, send_u_e, u, u_s, u_e, n_tds, n_rhs, coeffs_s, coeffs_e, coeffs, ffr, fbc, faf)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(out), device, dimension(:, :, :) :: du
real(kind=dp), intent(out), device, dimension(:, :, :) :: send_u_s
real(kind=dp), intent(out), device, dimension(:, :, :) :: send_u_e
real(kind=dp), intent(in), device, dimension(:, :, :) :: u
real(kind=dp), intent(in), device, dimension(:, :, :) :: u_s
real(kind=dp), intent(in), device, dimension(:, :, :) :: u_e
integer, intent(in), value :: n_tds
integer, intent(in), value :: n_rhs
real(kind=dp), intent(in), device, dimension(:, :) :: coeffs_s
real(kind=dp), intent(in), device, dimension(:, :) :: coeffs_e
real(kind=dp), intent(in), device, dimension(:) :: coeffs
real(kind=dp), intent(in), device, dimension(:) :: ffr
real(kind=dp), intent(in), device, dimension(:) :: fbc
real(kind=dp), intent(in), device, dimension(:) :: faf
Called by
Call graph
exec_dist_tds_compact calls der_univ_dist
tds_solve_dist calls exec_dist_tds_compact
tds_solve_cuda calls tds_solve_dist