deriv_1st – x3d2
deriv_1st Subroutine
88 statements
Source File
public subroutine deriv_1st(self, delta, scheme, bc_start, bc_end, sym)
Type Bound
tdsops_t
Arguments
Type Intent Optional Attributes Name
class(tdsops_t), intent(inout) :: self
real(kind=dp), intent(in) :: delta
character(len=*), intent(in) :: scheme
integer, intent(in) :: bc_start
integer, intent(in) :: bc_end
logical, intent(in), optional :: sym
Calls
Called by
Call graph
deriv_1st calls preprocess_dist, preprocess_thom
tdsops_init calls deriv_1st
tdsops_t calls tdsops_init
cuda_tdsops_init calls tdsops_init
cuda_tdsops_t calls cuda_tdsops_init