divergence_v2c – x3d2
divergence_v2c Subroutine
50 statements
Source File
public subroutine divergence_v2c(self, div_u, u, v, w, x_stagder_v2c, x_interpl_v2c, y_stagder_v2c, y_interpl_v2c, z_stagder_v2c, z_interpl_v2c)
Divergence of a vector field (u, v, w).
Evaluated at the cell centers (data_loc=CELL) Input fields are at vertices (data_loc=VERT)
Input fields are in DIR_X data layout. Output field is in DIR_Z data layout.
Type Bound
vector_calculus_t
Arguments
Type Intent Optional Attributes Name
class(vector_calculus_t) :: self
class(field_t), intent(inout) :: div_u
class(field_t), intent(in) :: u
class(field_t), intent(in) :: v
class(field_t), intent(in) :: w
class(tdsops_t), intent(in) :: x_stagder_v2c
class(tdsops_t), intent(in) :: x_interpl_v2c
class(tdsops_t), intent(in) :: y_stagder_v2c
class(tdsops_t), intent(in) :: y_interpl_v2c
class(tdsops_t), intent(in) :: z_stagder_v2c
class(tdsops_t), intent(in) :: z_interpl_v2c
Calls
Called by
Call graph
divergence_v2c calls get_block, release_block, reorder, tds_solve, vecadd
get_block calls get_padded_dims, create_block, set_shape
get_padded_dims_dir calls get_n_groups
get_padded_dims_phi calls get_padded_dims
get_n_groups_phi calls get_n_groups
divergence_v2p calls divergence_v2c
pressure_correction calls divergence_v2p
print_div_max_mean calls divergence_v2p
postprocess_generic calls print_div_max_mean
postprocess_tgv calls print_div_max_mean
run calls pressure_correction
xcompact calls run