divergence_v2p – x3d2
divergence_v2p Subroutine
7 statements
Source File
public subroutine divergence_v2p(self, div_u, u, v, w)
Wrapper for divergence_v2p
Type Bound
solver_t
Arguments
Type Intent Optional Attributes Name
class(solver_t) :: self
class(field_t), intent(inout) :: div_u
class(field_t), intent(in) :: u
class(field_t), intent(in) :: v
class(field_t), intent(in) :: w
Calls
Called by
Call graph
divergence_v2p calls divergence_v2c
divergence_v2c calls get_block, release_block, reorder, tds_solve, vecadd
get_block calls create_block, set_shape
pressure_correction calls divergence_v2p
print_div_max_mean calls divergence_v2p
postprocess_channel calls print_div_max_mean
postprocess_cylinder calls print_div_max_mean
postprocess_generic calls print_div_max_mean
postprocess_tgv calls print_div_max_mean
run calls pressure_correction
xcompact calls run