exec_dist_transeq_compact – x3d2
exec_dist_transeq_compact Subroutine
44 statements
Source File
public subroutine exec_dist_transeq_compact(rhs_du, dud, d2u, du_send_s, du_send_e, du_recv_s, du_recv_e, dud_send_s, dud_send_e, dud_recv_s, dud_recv_e, d2u_send_s, d2u_send_e, d2u_recv_s, d2u_recv_e, u, u_recv_s, u_recv_e, v, v_recv_s, v_recv_e, tdsops_du, tdsops_dud, tdsops_d2u, nu, nproc, pprev, pnext, n_groups)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(out), dimension(:, :, :) :: rhs_du
The result array, it is also used as temporary storage
real(kind=dp), intent(out), dimension(:, :, :) :: dud
Temporary storage arrays
real(kind=dp), intent(out), dimension(:, :, :) :: d2u
Temporary storage arrays
real(kind=dp), intent(out), dimension(:, :, :) :: du_send_s
real(kind=dp), intent(out), dimension(:, :, :) :: du_send_e
real(kind=dp), intent(out), dimension(:, :, :) :: du_recv_s
real(kind=dp), intent(out), dimension(:, :, :) :: du_recv_e
real(kind=dp), intent(out), dimension(:, :, :) :: dud_send_s
real(kind=dp), intent(out), dimension(:, :, :) :: dud_send_e
real(kind=dp), intent(out), dimension(:, :, :) :: dud_recv_s
real(kind=dp), intent(out), dimension(:, :, :) :: dud_recv_e
real(kind=dp), intent(out), dimension(:, :, :) :: d2u_send_s
real(kind=dp), intent(out), dimension(:, :, :) :: d2u_send_e
real(kind=dp), intent(out), dimension(:, :, :) :: d2u_recv_s
real(kind=dp), intent(out), dimension(:, :, :) :: d2u_recv_e
real(kind=dp), intent(in), dimension(:, :, :) :: u
real(kind=dp), intent(in), dimension(:, :, :) :: u_recv_s
real(kind=dp), intent(in), dimension(:, :, :) :: u_recv_e
real(kind=dp), intent(in), dimension(:, :, :) :: v
real(kind=dp), intent(in), dimension(:, :, :) :: v_recv_s
real(kind=dp), intent(in), dimension(:, :, :) :: v_recv_e
type(tdsops_t), intent(in) :: tdsops_du
type(tdsops_t), intent(in) :: tdsops_dud
type(tdsops_t), intent(in) :: tdsops_d2u
real(kind=dp), intent(in) :: nu
integer, intent(in) :: nproc
integer, intent(in) :: pprev
integer, intent(in) :: pnext
integer, intent(in) :: n_groups
Calls
Called by
Call graph
exec_dist_transeq_compact calls der_univ_dist, der_univ_fused_subs, sendrecv_fields
sendrecv_fields calls mpi_irecv, mpi_isend, mpi_waitall
transeq_omp_dist calls exec_dist_transeq_compact
transeq_species_omp calls exec_dist_transeq_compact
transeq_x_omp calls transeq_omp_dist
transeq_y_omp calls transeq_omp_dist
transeq_z_omp calls transeq_omp_dist