exec_dist_transeq_3fused – x3d2
exec_dist_transeq_3fused Subroutine
17 statements
Source File
public subroutine exec_dist_transeq_3fused(r_du, u, u_recv_s, u_recv_e, v, v_recv_s, v_recv_e, dud, d2u, du_send_s, du_send_e, du_recv_s, du_recv_e, dud_send_s, dud_send_e, dud_recv_s, dud_recv_e, d2u_send_s, d2u_send_e, d2u_recv_s, d2u_recv_e, tdsops_du, tdsops_dud, tdsops_d2u, nu, nproc, pprev, pnext, blocks, threads)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(out), device, dimension(:, :, :) :: r_du
The result array, it is also used as temporary storage
real(kind=dp), intent(in), device, dimension(:, :, :) :: u
real(kind=dp), intent(in), device, dimension(:, :, :) :: u_recv_s
real(kind=dp), intent(in), device, dimension(:, :, :) :: u_recv_e
real(kind=dp), intent(in), device, dimension(:, :, :) :: v
real(kind=dp), intent(in), device, dimension(:, :, :) :: v_recv_s
real(kind=dp), intent(in), device, dimension(:, :, :) :: v_recv_e
real(kind=dp), intent(out), device, dimension(:, :, :) :: dud
real(kind=dp), intent(out), device, dimension(:, :, :) :: d2u
real(kind=dp), intent(out), device, dimension(:, :, :) :: du_send_s
real(kind=dp), intent(out), device, dimension(:, :, :) :: du_send_e
real(kind=dp), intent(out), device, dimension(:, :, :) :: du_recv_s
real(kind=dp), intent(out), device, dimension(:, :, :) :: du_recv_e
real(kind=dp), intent(out), device, dimension(:, :, :) :: dud_send_s
real(kind=dp), intent(out), device, dimension(:, :, :) :: dud_send_e
real(kind=dp), intent(out), device, dimension(:, :, :) :: dud_recv_s
real(kind=dp), intent(out), device, dimension(:, :, :) :: dud_recv_e
real(kind=dp), intent(out), device, dimension(:, :, :) :: d2u_send_s
real(kind=dp), intent(out), device, dimension(:, :, :) :: d2u_send_e
real(kind=dp), intent(out), device, dimension(:, :, :) :: d2u_recv_s
real(kind=dp), intent(out), device, dimension(:, :, :) :: d2u_recv_e
type(cuda_tdsops_t), intent(in) :: tdsops_du
type(cuda_tdsops_t), intent(in) :: tdsops_dud
type(cuda_tdsops_t), intent(in) :: tdsops_d2u
real(kind=dp), intent(in) :: nu
integer, intent(in) :: nproc
integer, intent(in) :: pprev
integer, intent(in) :: pnext
type(dim3), intent(in) :: blocks
type(dim3), intent(in) :: threads
Calls
Called by
Call graph
exec_dist_transeq_3fused calls sendrecv_3fields, transeq_3fused_dist, transeq_3fused_subs
sendrecv_3fields calls mpi_irecv, mpi_isend, mpi_waitall
transeq_cuda_dist calls exec_dist_transeq_3fused
transeq_species_cuda calls exec_dist_transeq_3fused
transeq_x_cuda calls transeq_cuda_dist
transeq_y_cuda calls transeq_cuda_dist
transeq_z_cuda calls transeq_cuda_dist