fft_postprocess_110_cuda – x3d2
fft_postprocess_110_cuda Subroutine
17 statements
Source File
public subroutine fft_postprocess_110_cuda(self)
Spectral post-processing for 110 case (R2C Z-transpose) 7 separate kernel launches to avoid cross-block race conditions. Spectral array is (nz/2+1, nx, ny) = (nx_spec, ny_spec, nz_spec). Thread i->X (ny_spec), blockIdx%y k->Y (nz_spec), serial j->Z (nx_spec).
Type Bound
cuda_poisson_fft_t
Arguments
Type Intent Optional Attributes Name
class(cuda_poisson_fft_t) :: self
Calls
Call graph
fft_postprocess_110_cuda calls dim3, process_spectral_110_norm_z, process_spectral_110_poisson, process_spectral_110_x_pair_bw, process_spectral_110_x_pair_fw, process_spectral_110_y_pair_bw, process_spectral_110_y_pair_fw, process_spectral_110_z_bw