field_set_face_cuda – x3d2
field_set_face_cuda Subroutine
30 statements
Source File
public subroutine field_set_face_cuda(self, f, c_start, c_end, face)
m_base_backend
Type Bound
cuda_backend_t
Arguments
Type Intent Optional Attributes Name
class(cuda_backend_t) :: self
class(field_t), intent(inout) :: f
real(kind=dp), intent(in) :: c_start
real(kind=dp), intent(in) :: c_end
integer, intent(in) :: face
Calls
Call graph
field_set_face_cuda calls dim3, field_set_y_face, get_dims, resolve_field_t
get_dims calls get_dims_dataloc