field_max_mean_omp – x3d2
field_max_mean_omp Subroutine
60 statements
Source File
public subroutine field_max_mean_omp(self, max_val, mean_val, f, enforced_data_loc)
m_base_backend
Type Bound
omp_backend_t
Arguments
Type Intent Optional Attributes Name
class(omp_backend_t) :: self
real(kind=dp), intent(out) :: max_val
real(kind=dp), intent(out) :: mean_val
class(field_t), intent(in) :: f
integer, intent(in), optional :: enforced_data_loc
Calls
Call graph
field_max_mean_omp calls mpi_allreduce, get_padded_dims, get_dims, get_global_dims
get_dims calls get_dims_dataloc
get_global_dims calls get_dims_dataloc
get_padded_dims_dir calls get_n_groups
get_padded_dims_phi calls get_padded_dims
get_n_groups_phi calls get_n_groups