field_volume_integral_cuda – x3d2
field_volume_integral_cuda Function
25 statements
Source File
public function field_volume_integral_cuda(self, f) result(s)
volume integral of a field
Type Bound
cuda_backend_t
Arguments
Type Intent Optional Attributes Name
class(cuda_backend_t) :: self
class(field_t), intent(in) :: f
Return Value real(kind=dp)
Calls
Call graph
field_volume_integral_cuda calls dim3, mpi_allreduce, get_padded_dims, get_dims, resolve_field_t, volume_integral
get_dims calls get_dims_dataloc
volume_integral calls atomicadd
get_padded_dims_dir calls get_n_groups
get_padded_dims_phi calls get_padded_dims
get_n_groups_phi calls get_n_groups