field_volume_integral_omp – x3d2
field_volume_integral_omp Function
30 statements
Source File
public function field_volume_integral_omp(self, f) result(s)
volume integral of a field
Type Bound
omp_backend_t
Arguments
Type Intent Optional Attributes Name
class(omp_backend_t) :: self
class(field_t), intent(in) :: f
Return Value real(kind=dp)
Calls
Call graph
field_volume_integral_omp calls mpi_allreduce, get_dims
get_dims calls get_dims_dataloc