field_set_face_from_field_cuda – x3d2
field_set_face_from_field_cuda Subroutine
43 statements
Source File
public subroutine field_set_face_from_field_cuda(self, f, f_start, c_end, face, bc_start, bc_end, flow_rate_diff)
Set a face of f using values supplied by another field f_start. Both fields must be DIR_X VERT pencil-layout. X_FACE uses the inlet plane (pencil index 1) of f_start plus a convective outflow update at the right face. Y_FACE copies the bottom and top y-pencil planes of f_start onto the corresponding planes of f (Dirichlet only).
Type Bound
cuda_backend_t
Arguments
Type Intent Optional Attributes Name
class(cuda_backend_t) :: self
class(field_t), intent(inout) :: f
class(field_t), intent(in) :: f_start
real(kind=dp), intent(in) :: c_end
integer, intent(in) :: face
integer, intent(in), optional :: bc_start
integer, intent(in), optional :: bc_end
real(kind=dp), intent(in), optional :: flow_rate_diff
Calls
Call graph
field_set_face_from_field_cuda calls dim3, field_set_x_face_from_field, field_set_y_face_from_field, get_dims, resolve_field_t
get_dims calls get_dims_dataloc