field_max_mean_cuda – x3d2
field_max_mean_cuda Subroutine
51 statements
Source File
public subroutine field_max_mean_cuda(self, max_val, mean_val, f, enforced_data_loc)
m_base_backend
Type Bound
cuda_backend_t
Arguments
Type Intent Optional Attributes Name
class(cuda_backend_t) :: self
real(kind=dp), intent(out) :: max_val
real(kind=dp), intent(out) :: mean_val
class(field_t), intent(in) :: f
integer, intent(in), optional :: enforced_data_loc
Calls
Call graph
field_max_mean_cuda calls dim3, mpi_allreduce, get_padded_dims, field_max_sum, get_dims, get_global_dims, resolve_field_t
field_max_sum calls atomicadd, atomicmax
get_dims calls get_dims_dataloc
get_global_dims calls get_dims_dataloc
get_padded_dims_dir calls get_n_groups
get_padded_dims_phi calls get_padded_dims
get_n_groups_phi calls get_n_groups