get_field_dims_phi_dataloc – x3d2
get_field_dims_phi_dataloc Function
7 statements
Source File
public pure function get_field_dims_phi_dataloc(self, phi, data_loc) result(dims)
Getter for the dimensions of field phi where data is located on data_loc
Type Bound
mesh_t
Arguments
Type Intent Optional Attributes Name
class(mesh_t), intent(in) :: self
class(field_t), intent(in) :: phi
integer, intent(in) :: data_loc
Return Value integer, dimension(3)
Calls
Called by
Call graph
get_field_dims_phi_dataloc calls get_field_dims
get_field_dims_dir calls get_n, get_n_groups
get_field_dims_phi calls get_field_dims
get_n_groups_phi calls get_n_groups
get_n_phi calls get_n
scalar_product_omp calls get_field_dims