get_n_groups_dir – x3d2
get_n_groups_dir Function
6 statements
Source File
public pure function get_n_groups_dir(self, dir) result(n_groups)
Getter for the number of groups for fields in direction dir
Type Bound
mesh_t
Arguments
Type Intent Optional Attributes Name
class(mesh_t), intent(in) :: self
integer, intent(in) :: dir
Return Value integer
Called by
Call graph
get_field_dims_dir calls get_n_groups
get_n_groups_phi calls get_n_groups
get_padded_dims_dir calls get_n_groups
init calls get_n_groups, get_block
tds_solve_cuda calls get_n_groups, tds_solve_dist
tds_solve_dist calls get_n_groups
transeq_cuda_dist calls get_n_groups, get_block
transeq_omp_dist calls get_n_groups, get_block
transeq_species_cuda calls get_n_groups, get_block
transeq_species_omp calls get_n_groups, get_block
cuda_backend_t calls init
omp_backend_t calls init
tds_solve_omp calls tds_solve_dist
transeq_x_cuda calls transeq_cuda_dist
transeq_x_omp calls transeq_omp_dist
transeq_y_cuda calls transeq_cuda_dist
transeq_y_omp calls transeq_omp_dist
transeq_z_cuda calls transeq_cuda_dist
transeq_z_omp calls transeq_omp_dist
allocator_init calls get_padded_dims
field_max_mean_cuda calls get_padded_dims
field_max_mean_omp calls get_padded_dims
field_volume_integral_cuda calls get_padded_dims
get_block calls get_padded_dims
get_field_dims_phi calls get_field_dims
get_field_dims_phi_dataloc calls get_field_dims
get_index_reordering_dirs calls get_padded_dims
get_padded_dims_phi calls get_padded_dims
reorder_cuda calls get_padded_dims, get_block
reorder_omp calls get_padded_dims, get_index_reordering
scalar_product_cuda calls get_padded_dims
scalar_product_omp calls get_field_dims, get_block, get_field_data
sum_intox_omp calls get_padded_dims, get_index_reordering
sum_yintox_cuda calls get_padded_dims
sum_zintox_cuda calls get_padded_dims
vecadd_omp calls get_padded_dims
veccopy_omp calls get_padded_dims
allocator_t calls allocator_init
get_index_reordering calls get_index_reordering_dirs, get_index_reordering_rdr
curl calls get_block, curl
divergence_v2c calls get_block
get_field_data calls get_block
gradient_c2v calls get_block
initial_conditions_channel calls get_block, set_field_data
laplacian calls get_block
poisson_fft calls get_block
pressure_correction calls get_block, divergence_v2p, gradient_p2v
print_div_max_mean calls get_block, divergence_v2p
print_enstrophy calls get_block, curl
run calls get_block, pressure_correction, handle_io_step
set_field_data calls get_block
set_init calls get_block, set_field_data
sum_yintox_omp calls sum_intox_omp
sum_zintox_omp calls sum_intox_omp
transeq_default calls get_block, transeq_species
transeq_lowmem calls get_block, transeq_species
transeq_species calls get_block
solver_t calls init
time_intg_t calls init
case_init calls init, handle_restart
divergence_v2p calls divergence_v2c
get_index_reordering_rdr calls get_index_reordering
gradient_p2v calls gradient_c2v
initial_conditions_tgv calls set_init
postprocess_channel calls print_div_max_mean, print_enstrophy
postprocess_generic calls print_div_max_mean, print_enstrophy
postprocess_tgv calls print_div_max_mean, print_enstrophy
xcompact calls run
case_channel_init calls case_init
case_generic_init calls case_init
case_tgv_init calls case_init
case_channel_t calls case_channel_init
case_generic_t calls case_generic_init
case_tgv_t calls case_tgv_init