get_field_dims_dir – x3d2
get_field_dims_dir Function
15 statements
Source File
public pure function get_field_dims_dir(self, dir, data_loc) result(dims)
Getter for the dimensions of an array directed along dir where data would be located on data_loc
Type Bound
mesh_t
Arguments
Type Intent Optional Attributes Name
class(mesh_t), intent(in) :: self
integer, intent(in) :: dir
integer, intent(in) :: data_loc
Return Value integer, dimension(3)
Calls
Called by
Call graph
get_field_dims_dir calls get_n, get_n_groups
get_n_groups_phi calls get_n_groups
get_n_phi calls get_n
get_field_dims_phi calls get_field_dims
get_field_dims_phi_dataloc calls get_field_dims
scalar_product_omp calls get_field_dims