get_km_im – x3d2
get_km_im Function
6 statements
Source File
public function get_km_im(self, i, j, k) result(re)
Type Bound
poisson_fft_t
Arguments
Type Intent Optional Attributes Name
class(poisson_fft_t) :: self
integer, intent(in) :: i
integer, intent(in) :: j
integer, intent(in) :: k
Return Value real(kind=dp)
Calls
Called by
Call graph
get_km_im calls get_imag, get_km
get_km calls get_imag, get_real
stretching_matrix calls get_km_im
base_init calls stretching_matrix