get_real – x3d2
get_real Function
5 statements
Source File
public function get_real(complx) result(re)
Arguments
Type Intent Optional Attributes Name
complex(kind=dp), intent(in) :: complx
Return Value real(kind=dp)
Called by
Call graph
get_km calls get_real
get_km_re calls get_real, get_km
stretching_matrix calls get_real, get_km, get_km_re, get_km_im
base_init calls stretching_matrix
get_km_im calls get_km