get_dims_dataloc – x3d2
get_dims_dataloc Function
33 statements
Source File
public pure function get_dims_dataloc(data_loc, vert_dims, cell_dims) result(dims)
Getter for domain dimensions
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: data_loc
integer, intent(in), dimension(3) :: vert_dims
integer, intent(in), dimension(3) :: cell_dims
Return Value integer, dimension(3)
Called by
Call graph
get_dims calls get_dims_dataloc
get_global_dims calls get_dims_dataloc
base_init calls get_dims, get_global_dims
boundary_conditions_channel calls get_global_dims
compute_outflow_params calls get_dims
field_max_mean_cuda calls get_dims, get_global_dims
field_max_mean_omp calls get_dims, get_global_dims
field_set_face_cuda calls get_dims
field_set_face_omp calls get_dims
field_volume_integral_cuda calls get_dims
field_volume_integral_omp calls get_dims
init calls get_global_dims
initial_conditions_channel calls get_dims
initial_conditions_cylinder calls get_dims
prepare_field_buffers calls get_dims, get_global_dims
scalar_product_cuda calls get_dims
scalar_product_omp calls get_dims
set_init calls get_dims
slice_max_sum_cuda calls get_dims
slice_max_sum_omp calls get_dims
write_single_field_to_buffer calls get_dims, get_global_dims
xcompact calls get_dims, run
solver_t calls init
apply_outflow_bc_cylinder calls compute_outflow_params
case_init calls init, handle_restart
initial_conditions_tgv calls set_init
boundary_conditions_cylinder calls apply_outflow_bc_cylinder
case_channel_init calls case_init
case_cylinder_init calls case_init
case_generic_init calls case_init
case_tgv_init calls case_init
pre_correction_cylinder calls apply_outflow_bc_cylinder
run calls handle_io_step, update_stats
case_channel_t calls case_channel_init
case_cylinder_t calls case_cylinder_init
case_generic_t calls case_generic_init
case_tgv_t calls case_tgv_init