get_coordinates – x3d2
get_coordinates Function
48 statements
Source File
public pure function get_coordinates(self, i, j, k, data_loc_op) result(coords)
Get the coordinates of a vertex with i, j, k local cartesian indices Avoid calling this in hot loops
Type Bound
mesh_t
Arguments
Type Intent Optional Attributes Name
class(mesh_t), intent(in) :: self
integer, intent(in) :: i
integer, intent(in) :: j
integer, intent(in) :: k
integer, intent(in), optional :: data_loc_op
Return Value real(kind=dp), dimension(3)
Called by
Call graph
generate_coordinates calls get_coordinates
initial_conditions_channel calls get_coordinates
initial_conditions_cylinder calls get_coordinates
set_init calls get_coordinates
initial_conditions_tgv calls set_init
run calls handle_io_step
xcompact calls run