get_n_groups – x3d2
get_n_groups Function
7 statements
Source File
public function get_n_groups(self, dir) result(n_groups)
Type Bound
allocator_t
Arguments
Type Intent Optional Attributes Name
class(allocator_t), intent(inout) :: self
integer, intent(in) :: dir
Return Value integer
Called by
Call graph
init calls get_n_groups
tds_solve_cuda calls get_n_groups, tds_solve_dist
tds_solve_dist calls get_n_groups
transeq_cuda_dist calls get_n_groups
transeq_omp_dist calls get_n_groups
transeq_species_cuda calls get_n_groups
transeq_species_omp calls get_n_groups
cuda_backend_t calls init
omp_backend_t calls init
tds_solve_omp calls tds_solve_dist
transeq_x_cuda calls transeq_cuda_dist
transeq_x_omp calls transeq_omp_dist
transeq_y_cuda calls transeq_cuda_dist
transeq_y_omp calls transeq_omp_dist
transeq_z_cuda calls transeq_cuda_dist
transeq_z_omp calls transeq_omp_dist