get_output_dimensions – x3d2
get_output_dimensions Subroutine
32 statements
Source File
public subroutine get_output_dimensions(shape_dims, start_dims, count_dims, stride_factors, output_shape, output_start, output_count, output_dims_local, last_shape_dims, last_stride_factors, last_output_shape)
Arguments
Type Intent Optional Attributes Name
integer(kind=i8), intent(in), dimension(3) :: shape_dims
integer(kind=i8), intent(in), dimension(3) :: start_dims
integer(kind=i8), intent(in), dimension(3) :: count_dims
integer, intent(in), dimension(3) :: stride_factors
integer(kind=i8), intent(out), dimension(3) :: output_shape
integer(kind=i8), intent(out), dimension(3) :: output_start
integer(kind=i8), intent(out), dimension(3) :: output_count
integer, intent(out), dimension(3) :: output_dims_local
integer(kind=i8), intent(inout), optional, dimension(3) :: last_shape_dims
integer, intent(inout), optional, dimension(3) :: last_stride_factors
integer(kind=i8), intent(inout), optional, dimension(3) :: last_output_shape
Called by
Call graph
prepare_field_buffers calls get_output_dimensions
write_single_field_to_buffer calls get_output_dimensions
run calls handle_io_step
xcompact calls run