get_km – x3d2
get_km Function
6 statements
Source File
public function get_km(self, i, j, k) result(km)
Type Bound
poisson_fft_t
Arguments
Type Intent Optional Attributes Name
class(poisson_fft_t) :: self
integer, intent(in) :: i
integer, intent(in) :: j
integer, intent(in) :: k
Return Value complex(kind=dp)
Calls
Called by
Call graph
get_km calls get_imag, get_real
get_km_im calls get_km
get_km_re calls get_km
stretching_matrix calls get_km, get_km_im, get_km_re
base_init calls stretching_matrix