get_padded_dims – x3d2
get_padded_dims Function
7 statements
Source File
public function get_padded_dims(self, dir) result(dims)
Type Bound
allocator_t
Arguments
Type Intent Optional Attributes Name
class(allocator_t), intent(inout) :: self
integer, intent(in) :: dir
Return Value integer, (3)
Called by
Call graph
field_max_mean_cuda calls get_padded_dims
field_max_mean_omp calls get_padded_dims
field_volume_integral_cuda calls get_padded_dims
reorder_cuda calls get_padded_dims
reorder_omp calls get_padded_dims
scalar_product_cuda calls get_padded_dims
sum_intox_omp calls get_padded_dims
sum_yintox_cuda calls get_padded_dims
sum_zintox_cuda calls get_padded_dims
sum_yintox_omp calls sum_intox_omp
sum_zintox_omp calls sum_intox_omp