get_dims – x3d2
get_dims Function
6 statements
Source File
public pure function get_dims(self, data_loc) result(dims)
Getter for local domain dimensions
Type Bound
mesh_t
Arguments
Type Intent Optional Attributes Name
class(mesh_t), intent(in) :: self
integer, intent(in) :: data_loc
Return Value integer, dimension(3)
Calls
Called by
Call graph
get_dims calls get_dims_dataloc
base_init calls get_dims
compute_outflow_params calls get_dims
define_bc_channel calls get_dims
define_bc_cylinder calls get_dims, compute_outflow_params
field_max_mean_cuda calls get_dims
field_max_mean_omp calls get_dims
field_set_face_cuda calls get_dims
field_set_face_from_field_cuda calls get_dims
field_set_face_from_field_omp calls get_dims
field_set_face_omp calls get_dims
field_volume_integral_cuda calls get_dims
field_volume_integral_omp calls get_dims
initial_conditions_channel calls get_dims
initial_conditions_cylinder calls get_dims
prepare_field_buffers calls get_dims
scalar_product_cuda calls get_dims
scalar_product_omp calls get_dims
set_init calls get_dims
slice_max_sum_cuda calls get_dims
slice_max_sum_omp calls get_dims
write_single_field_to_buffer calls get_dims
xcompact calls get_dims, run
initial_conditions_tgv calls set_init
case_init calls handle_restart
run calls handle_io_step, update_stats
case_channel_init calls case_init
case_cylinder_init calls case_init
case_generic_init calls case_init
case_tgv_init calls case_init
case_channel_t calls case_channel_init
case_cylinder_t calls case_cylinder_init
case_generic_t calls case_generic_init
case_tgv_t calls case_tgv_init