get_rdr_from_dirs – x3d2
get_rdr_from_dirs Function
4 statements
Source File
public pure function get_rdr_from_dirs(dir_from, dir_to) result(rdr_dir)
Returns RDR_?2? value based on two direction inputs
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: dir_from
integer, intent(in) :: dir_to
Return Value integer
Called by
Call graph
get_field_data calls get_rdr_from_dirs
set_field_data calls get_rdr_from_dirs
define_bc_channel calls set_field_data
define_bc_cylinder calls set_field_data
initial_conditions_channel calls set_field_data
initial_conditions_cylinder calls set_field_data
scalar_product_omp calls get_field_data
set_init calls set_field_data
setup_field_arrays calls get_field_data
initial_conditions_tgv calls set_init
case_init calls handle_restart
run calls handle_io_step, update_stats
case_channel_init calls case_init
case_cylinder_init calls case_init
case_generic_init calls case_init
case_tgv_init calls case_init
xcompact calls run
case_channel_t calls case_channel_init
case_cylinder_t calls case_cylinder_init
case_generic_t calls case_generic_init
case_tgv_t calls case_tgv_init