get_imag – x3d2
get_imag Function
5 statements
Source File
public function get_imag(complx) result(im)
Arguments
Type Intent Optional Attributes Name
complex(kind=dp), intent(in) :: complx
Return Value real(kind=dp)
Called by
Call graph
get_km calls get_imag
get_km_im calls get_imag, get_km
stretching_matrix calls get_imag, get_km, get_km_im, get_km_re
base_init calls stretching_matrix
get_km_re calls get_km