get_global_dims – x3d2
get_global_dims Function
6 statements
Source File
public pure function get_global_dims(self, data_loc) result(dims)
Getter for local domain dimensions
Type Bound
mesh_t
Arguments
Type Intent Optional Attributes Name
class(mesh_t), intent(in) :: self
integer, intent(in) :: data_loc
Return Value integer, dimension(3)
Calls
Called by
Call graph
get_global_dims calls get_dims_dataloc
base_init calls get_global_dims
boundary_conditions_channel calls get_global_dims
field_max_mean_cuda calls get_global_dims
field_max_mean_omp calls get_global_dims
init calls get_global_dims
prepare_field_buffers calls get_global_dims
write_single_field_to_buffer calls get_global_dims
solver_t calls init
case_init calls init
case_channel_init calls case_init
case_cylinder_init calls case_init
case_generic_init calls case_init
case_tgv_init calls case_init
run calls handle_io_step
case_channel_t calls case_channel_init
case_cylinder_t calls case_cylinder_init
case_generic_t calls case_generic_init
case_tgv_t calls case_tgv_init
xcompact calls run