get_dirs_from_rdr – x3d2
get_dirs_from_rdr Subroutine
8 statements
Source File
public pure subroutine get_dirs_from_rdr(dir_from, dir_to, rdr_dir)
Arguments
Type Intent Optional Attributes Name
integer, intent(out) :: dir_from
integer, intent(out) :: dir_to
integer, intent(in) :: rdr_dir
Called by
Call graph
get_index_reordering_rdr calls get_dirs_from_rdr, get_index_reordering
reorder_omp calls get_dirs_from_rdr, get_index_reordering
get_index_reordering calls get_index_reordering_rdr
sum_intox_omp calls get_index_reordering
sum_yintox_omp calls sum_intox_omp
sum_zintox_omp calls sum_intox_omp