get_shape – x3d2
get_shape Function
6 statements
Source File
public function get_shape(self) result(dims)
Type Bound
field_t
Arguments
Type Intent Optional Attributes Name
class(field_t) :: self
Return Value integer, (3)
Called by
Call graph
case_init calls handle_restart
run calls handle_io_step
case_channel_init calls case_init
case_cylinder_init calls case_init
case_generic_init calls case_init
case_tgv_init calls case_init
xcompact calls run
case_channel_t calls case_channel_init
case_cylinder_t calls case_cylinder_init
case_generic_t calls case_generic_init
case_tgv_t calls case_tgv_init