get_n_dir – x3d2
get_n_dir Function
41 statements
Source File
public pure function get_n_dir(self, dir, data_loc) result(n)
Getter for the main dimension a field oriented along dir with data on data_loc
Type Bound
mesh_t
Arguments
Type Intent Optional Attributes Name
class(mesh_t), intent(in) :: self
integer, intent(in) :: dir
integer, intent(in) :: data_loc
Return Value integer
Called by
Call graph
allocate_tdsops calls get_n
get_field_dims_dir calls get_n
get_n_phi calls get_n
transeq_cuda_dist calls get_n
transeq_omp_dist calls get_n
init calls allocate_tdsops
transeq_x_cuda calls transeq_cuda_dist
transeq_x_omp calls transeq_omp_dist
transeq_y_cuda calls transeq_cuda_dist
transeq_y_omp calls transeq_omp_dist
transeq_z_cuda calls transeq_cuda_dist
transeq_z_omp calls transeq_omp_dist
solver_t calls init
case_init calls init
get_field_dims_phi calls get_field_dims
get_field_dims_phi_dataloc calls get_field_dims
scalar_product_omp calls get_field_dims
case_channel_init calls case_init
case_generic_init calls case_init
case_tgv_init calls case_init
case_channel_t calls case_channel_init
case_generic_t calls case_generic_init
case_tgv_t calls case_tgv_init