get_argument – x3d2
get_argument Function
13 statements
Source File
public function get_argument(pos) result(arg)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: pos
Return Value character(len=:), allocatable
Called by
Call graph
case_channel_init calls get_argument, case_init
case_cylinder_init calls get_argument, case_init
init calls get_argument
xcompact calls get_argument
case_channel_t calls case_channel_init
case_cylinder_t calls case_cylinder_init
solver_t calls init
case_init calls init
case_generic_init calls case_init
case_tgv_init calls case_init
case_generic_t calls case_generic_init
case_tgv_t calls case_tgv_init