get_field_data – x3d2
get_field_data Subroutine
23 statements
Source File
public subroutine get_field_data(self, data, f, dir)
Extract data from field f optionally reordering into dir orientation. To output in same orientation as f, use call ...%get_field_data(data, f, f%dir)
Type Bound
base_backend_t
Arguments
Type Intent Optional Attributes Name
class(base_backend_t) :: self
real(kind=dp), intent(out), dimension(:, :, :) :: data
Output array
class(field_t), intent(in) :: f
Field
integer, intent(in), optional :: dir
Desired orientation of output array (defaults to Cartesian)
Calls
Called by
Call graph
get_field_data calls copy_f_to_data, get_block, get_rdr_from_dirs, release_block, reorder
get_block calls get_padded_dims, create_block, set_shape
get_padded_dims_dir calls get_n_groups
get_padded_dims_phi calls get_padded_dims
get_n_groups_phi calls get_n_groups
run calls get_field_data
scalar_product_omp calls get_field_data
xcompact calls run