gradient_p2v – x3d2
gradient_p2v Subroutine
7 statements
Source File
public subroutine gradient_p2v(self, dpdx, dpdy, dpdz, pressure)
Wrapper for gradient_p2v
Type Bound
solver_t
Arguments
Type Intent Optional Attributes Name
class(solver_t) :: self
class(field_t), intent(inout) :: dpdx
class(field_t), intent(inout) :: dpdy
class(field_t), intent(inout) :: dpdz
class(field_t), intent(in) :: pressure
Calls
Called by
Call graph
gradient_p2v calls gradient_c2v
gradient_c2v calls get_block, release_block, reorder, tds_solve
get_block calls create_block, set_shape
pressure_correction calls gradient_p2v
run calls pressure_correction
xcompact calls run