gradient_c2v – x3d2
gradient_c2v Subroutine
44 statements
Source File
public subroutine gradient_c2v(self, dpdx, dpdy, dpdz, p, x_stagder_c2v, x_interpl_c2v, y_stagder_c2v, y_interpl_c2v, z_stagder_c2v, z_interpl_c2v)
Gradient of a scalar field 'p'.
Evaluated at the vertices (data_loc=VERT) Input field is at cell centers (data_loc=CELL)
Input field is in DIR_Z data layout. Output fields (dpdx, dpdy, dpdz) are in DIR_X data layout.
Type Bound
vector_calculus_t
Arguments
Type Intent Optional Attributes Name
class(vector_calculus_t) :: self
class(field_t), intent(inout) :: dpdx
class(field_t), intent(inout) :: dpdy
class(field_t), intent(inout) :: dpdz
class(field_t), intent(in) :: p
class(tdsops_t), intent(in) :: x_stagder_c2v
class(tdsops_t), intent(in) :: x_interpl_c2v
class(tdsops_t), intent(in) :: y_stagder_c2v
class(tdsops_t), intent(in) :: y_interpl_c2v
class(tdsops_t), intent(in) :: z_stagder_c2v
class(tdsops_t), intent(in) :: z_interpl_c2v
Calls
Called by
Call graph
gradient_c2v calls get_block, release_block, reorder, tds_solve
get_block calls get_padded_dims, create_block, set_shape
get_padded_dims_dir calls get_n_groups
get_padded_dims_phi calls get_padded_dims
get_n_groups_phi calls get_n_groups
gradient_p2v calls gradient_c2v
pressure_correction calls gradient_p2v
run calls pressure_correction
xcompact calls run