init – x3d2
init Function
61 statements
Source File
public function init(backend, mesh, host_allocator) result(solver)
Arguments
Type Intent Optional Attributes Name
class(base_backend_t), intent(inout), target :: backend
type(mesh_t), intent(inout), target :: mesh
type(allocator_t), intent(inout), target :: host_allocator
Return Value type(solver_t)
Calls
Called by
Call graph
init calls init_poisson_fft, allocate_tdsops, get_argument, get_block, get_global_dims, is_root
allocate_tdsops calls alloc_tdsops, get_n
get_block calls create_block, set_shape
get_global_dims calls get_dims_dataloc
get_n_phi calls get_n
solver_t calls init
case_init calls init
case_channel_init calls case_init
case_cylinder_init calls case_init
case_generic_init calls case_init
case_tgv_init calls case_init
case_channel_t calls case_channel_init
case_cylinder_t calls case_cylinder_init
case_generic_t calls case_generic_init
case_tgv_t calls case_tgv_init