initial_conditions_cylinder – x3d2
initial_conditions_cylinder Subroutine
30 statements
Source File
public subroutine initial_conditions_cylinder(self)
Type Bound
case_cylinder_t
Arguments
Type Intent Optional Attributes Name
class(case_cylinder_t) :: self
Calls
Call graph
initial_conditions_cylinder calls fill, get_block, get_dims, release_block, set_data_loc, set_field_data
get_block calls create_block, set_shape
get_dims calls get_dims_dataloc
set_field_data calls get_block, release_block, copy_data_to_f, get_rdr_from_dirs, reorder