initial_conditions_channel – x3d2
initial_conditions_channel Subroutine
42 statements
Source File
public subroutine initial_conditions_channel(self)
Type Bound
case_channel_t
Arguments
Type Intent Optional Attributes Name
class(case_channel_t) :: self
Calls
Call graph
initial_conditions_channel calls get_block, get_coordinates, get_dims, release_block, set_data_loc, set_field_data
get_block calls create_block, set_shape
get_dims calls get_dims_dataloc
set_field_data calls get_block, release_block, copy_data_to_f, get_rdr_from_dirs, reorder