initial_conditions_tgv – x3d2
initial_conditions_tgv Subroutine
10 statements
Source File
public subroutine initial_conditions_tgv(self)
Type Bound
case_tgv_t
Arguments
Type Intent Optional Attributes Name
class(case_tgv_t) :: self
Calls
Call graph
initial_conditions_tgv calls fill, set_data_loc, set_init
set_init calls get_block, get_coordinates, get_dims, release_block, set_field_data
get_block calls get_padded_dims, create_block, set_shape
get_dims calls get_dims_dataloc
set_field_data calls get_block, release_block, copy_data_to_f, get_rdr_from_dirs, reorder
get_padded_dims_dir calls get_n_groups
get_padded_dims_phi calls get_padded_dims
get_n_groups_phi calls get_n_groups