init – x3d2
init Function
67 statements
Source File
public function init(backend, allocator, method, nvars)
Arguments
Type Intent Optional Attributes Name
class(base_backend_t), pointer :: backend
class(allocator_t), pointer :: allocator
character(len=3), intent(in) :: method
integer, intent(in), optional :: nvars
Return Value type(time_intg_t)
Calls
Called by
Call graph
init calls get_block
get_block calls get_padded_dims, create_block, set_shape
get_padded_dims_dir calls get_n_groups
get_padded_dims_phi calls get_padded_dims
get_n_groups_phi calls get_n_groups
time_intg_t calls init