interpl_c2v – x3d2
interpl_c2v Subroutine
24 statements
Source File
public subroutine interpl_c2v(self, p_out, p, x_interpl_c2v, y_interpl_c2v, z_interpl_c2v)
Interpolation of a scalar field from cell centres to vertices.
Input field is at cell centres (data_loc=CELL) in DIR_Z layout. Output field is at vertices (data_loc=VERT) in DIR_X layout.
Type Bound
vector_calculus_t
Arguments
Type Intent Optional Attributes Name
class(vector_calculus_t) :: self
class(field_t), intent(inout) :: p_out
class(field_t), intent(in) :: p
class(tdsops_t), intent(in) :: x_interpl_c2v
class(tdsops_t), intent(in) :: y_interpl_c2v
class(tdsops_t), intent(in) :: z_interpl_c2v
Calls
Called by
Call graph
interpl_c2v calls get_block, release_block, reorder, tds_solve
get_block calls create_block, set_shape
compute_pressure_vert calls interpl_c2v
run calls compute_pressure_vert
xcompact calls run