is_root – x3d2
is_root Function
5 statements
Source File
public pure function is_root(self) result(is_root_rank)
Returns wether or not the current rank is the root rank
Type Bound
par_t
Arguments
Type Intent Optional Attributes Name
class(par_t), intent(in) :: self
Return Value logical
Called by
Call graph
case_finalise calls is_root
decomposition_2decomp calls is_root
decomposition_generic calls is_root
init calls is_root
postprocess_channel calls is_root, print_div_max_mean, print_enstrophy
postprocess_cylinder calls is_root, print_div_max_mean, print_enstrophy
postprocess_generic calls is_root, print_div_max_mean, print_enstrophy
postprocess_tgv calls is_root, print_div_max_mean, print_enstrophy
print_div_max_mean calls is_root
print_enstrophy calls is_root
run calls is_root, case_finalise, handle_io_step
setup_field_arrays calls is_root
solver_t calls init
case_init calls init, handle_restart
mesh_init calls decomposition_2decomp, decomposition_generic
xcompact calls run
mesh_t calls mesh_init
case_channel_init calls case_init
case_cylinder_init calls case_init
case_generic_init calls case_init
case_tgv_init calls case_init
case_channel_t calls case_channel_init
case_cylinder_t calls case_cylinder_init
case_generic_t calls case_generic_init
case_tgv_t calls case_tgv_init