laplacian – x3d2
laplacian Subroutine
26 statements
Source File
public subroutine laplacian(self, lapl_u, u, x_der2nd, y_der2nd, z_der2nd)
Laplacian of a scalar field 'u'.
Evaluated at the data_loc defined by the input u field
Input and output fields are in DIR_X layout.
Type Bound
vector_calculus_t
Arguments
Type Intent Optional Attributes Name
class(vector_calculus_t) :: self
class(field_t), intent(inout) :: lapl_u
class(field_t), intent(in) :: u
class(tdsops_t), intent(in) :: x_der2nd
class(tdsops_t), intent(in) :: y_der2nd
class(tdsops_t), intent(in) :: z_der2nd
Calls
Call graph
laplacian calls get_block, release_block, reorder, sum_yintox, sum_zintox, tds_solve
get_block calls get_padded_dims, create_block, set_shape
get_padded_dims_dir calls get_n_groups
get_padded_dims_phi calls get_padded_dims
get_n_groups_phi calls get_n_groups