poisson_fft – x3d2
poisson_fft Subroutine
14 statements
Source File
public subroutine poisson_fft(self, pressure, div_u)
Arguments
Type Intent Optional Attributes Name
class(solver_t) :: self
class(field_t), intent(inout) :: pressure
class(field_t), intent(in) :: div_u
Calls
Call graph
poisson_fft calls fft_backward, fft_forward, fft_postprocess, get_block, release_block, reorder
get_block calls get_padded_dims, create_block, set_shape
get_padded_dims_dir calls get_n_groups
get_padded_dims_phi calls get_padded_dims
get_n_groups_phi calls get_n_groups