postprocess_generic – x3d2
postprocess_generic Subroutine
9 statements
Source File
public subroutine postprocess_generic(self, i, t)
Type Bound
case_generic_t
Arguments
Type Intent Optional Attributes Name
class(case_generic_t) :: self
integer, intent(in) :: i
real(kind=dp), intent(in) :: t
Calls
Call graph
postprocess_generic calls is_root, print_div_max_mean, print_enstrophy
print_div_max_mean calls is_root, mpi_allreduce, divergence_v2p, get_block, get_dims, get_field_data, release_block
print_enstrophy calls is_root, mpi_allreduce, curl, get_block, get_dims, get_field_data, release_block
curl calls curl, get_block, release_block, reorder, tds_solve, vecadd
divergence_v2p calls divergence_v2c
get_block calls get_padded_dims, create_block, set_shape
get_dims calls get_dims_dataloc
get_field_data calls get_block, release_block, copy_f_to_data, get_rdr_from_dirs, reorder
divergence_v2c calls get_block, release_block, reorder, tds_solve, vecadd
get_padded_dims_dir calls get_n_groups
get_padded_dims_phi calls get_padded_dims
get_n_groups_phi calls get_n_groups