postprocess_channel – x3d2
postprocess_channel Subroutine
10 statements
Source File
public subroutine postprocess_channel(self, iter, t)
Type Bound
case_channel_t
Arguments
Type Intent Optional Attributes Name
class(case_channel_t) :: self
integer, intent(in) :: iter
real(kind=dp), intent(in) :: t
Calls
Call graph
postprocess_channel calls is_root, write_step
write_step calls field_max_mean, write_step, curl, divergence_v2p, get_block, release_block, scalar_product
curl calls curl, get_block, release_block, reorder, tds_solve, vecadd
divergence_v2p calls divergence_v2c
get_block calls create_block, set_shape
divergence_v2c calls get_block, release_block, reorder, tds_solve, vecadd