postprocess_cylinder – x3d2
postprocess_cylinder Subroutine
11 statements
Source File
public subroutine postprocess_cylinder(self, iter, t)
Type Bound
case_cylinder_t
Arguments
Type Intent Optional Attributes Name
class(case_cylinder_t) :: self
integer, intent(in) :: iter
real(kind=dp), intent(in) :: t
Calls
Call graph
postprocess_cylinder calls is_root, print_div_max_mean, print_enstrophy
print_div_max_mean calls is_root, field_max_mean, divergence_v2p, get_block, release_block
print_enstrophy calls is_root, curl, get_block, release_block, scalar_product
curl calls curl, get_block, release_block, reorder, tds_solve, vecadd
divergence_v2p calls divergence_v2c
get_block calls create_block, set_shape
divergence_v2c calls get_block, release_block, reorder, tds_solve, vecadd