preprocess_thom – x3d2
preprocess_thom Subroutine
29 statements
Source File
public subroutine preprocess_thom(self, b)
Type Bound
tdsops_t
Arguments
Type Intent Optional Attributes Name
class(tdsops_t), intent(inout) :: self
real(kind=dp), intent(in), dimension(:) :: b
Called by
Call graph
deriv_1st calls preprocess_thom
deriv_2nd calls preprocess_thom
interpl_mid calls preprocess_thom
stagder_1st calls preprocess_thom
tdsops_init calls deriv_1st, deriv_2nd, interpl_mid, stagder_1st
tdsops_t calls tdsops_init
cuda_tdsops_init calls tdsops_init
cuda_tdsops_t calls cuda_tdsops_init