prepare_field_buffers – x3d2
prepare_field_buffers Subroutine
24 statements
Source File
public subroutine prepare_field_buffers(solver, stride_factors, field_names, data_loc, field_buffers, last_shape_dims, last_stride_factors, last_output_shape)
Arguments
Type Intent Optional Attributes Name
class(solver_t), intent(in) :: solver
integer, intent(in), dimension(3) :: stride_factors
character(len=*), intent(in), dimension(:) :: field_names
integer, intent(in) :: data_loc
type(field_buffer_map_t), intent(inout), allocatable :: field_buffers(:)
integer(kind=i8), intent(inout), dimension(3) :: last_shape_dims
integer, intent(inout), dimension(3) :: last_stride_factors
integer(kind=i8), intent(inout), dimension(3) :: last_output_shape
Calls
Called by
Call graph
prepare_field_buffers calls get_dims, get_global_dims, get_output_dimensions
get_dims calls get_dims_dataloc
get_global_dims calls get_dims_dataloc
run calls handle_io_step
xcompact calls run