pressure_correction – x3d2
pressure_correction Subroutine
22 statements
Source File
public subroutine pressure_correction(self, u, v, w)
Type Bound
solver_t
Arguments
Type Intent Optional Attributes Name
class(solver_t) :: self
class(field_t), intent(inout) :: u
class(field_t), intent(inout) :: v
class(field_t), intent(inout) :: w
Calls
Called by
Call graph
pressure_correction calls divergence_v2p, get_block, gradient_p2v, release_block, vecadd
divergence_v2p calls divergence_v2c
get_block calls create_block, set_shape
gradient_p2v calls gradient_c2v
divergence_v2c calls get_block, release_block, vecadd, reorder, tds_solve
gradient_c2v calls get_block, release_block, reorder, tds_solve
run calls pressure_correction
xcompact calls run