print_div_max_mean – x3d2
print_div_max_mean Subroutine
21 statements
Source File
public subroutine print_div_max_mean(self, u, v, w)
Reports the div(u) at cell centres
Type Bound
base_case_t
Arguments
Type Intent Optional Attributes Name
class(base_case_t), intent(in) :: self
class(field_t), intent(in) :: u
class(field_t), intent(in) :: v
class(field_t), intent(in) :: w
Calls
Called by
Call graph
print_div_max_mean calls mpi_allreduce, divergence_v2p, get_block, get_dims, get_field_data, is_root, release_block
divergence_v2p calls divergence_v2c
get_block calls get_padded_dims, create_block, set_shape
get_dims calls get_dims_dataloc
get_field_data calls get_block, release_block, copy_f_to_data, get_rdr_from_dirs, reorder
divergence_v2c calls get_block, release_block, reorder, tds_solve, vecadd
get_padded_dims_dir calls get_n_groups
get_padded_dims_phi calls get_padded_dims
get_n_groups_phi calls get_n_groups
postprocess_generic calls print_div_max_mean
postprocess_tgv calls print_div_max_mean