release_block – x3d2
release_block Subroutine
6 statements
Source File
public subroutine release_block(self, handle)
Release memory block pointed to by HANDLE to the block list. It is pushed to the front of the block list, in other words it is made the head block.
Type Bound
allocator_t
Arguments
Type Intent Optional Attributes Name
class(allocator_t), intent(inout) :: self
class(field_t), pointer :: handle
Called by
Call graph
cleanup_field_arrays calls release_block
compute_derived_fields calls release_block
curl calls release_block, curl
divergence_v2c calls release_block
finalize calls release_block
get_field_data calls release_block
gradient_c2v calls release_block
initial_conditions_channel calls release_block, set_field_data
initial_conditions_cylinder calls release_block, set_field_data
interpl_c2v calls release_block
laplacian calls release_block
poisson_fft calls release_block
pressure_correction calls release_block, divergence_v2p, gradient_p2v
print_div_max_mean calls release_block, divergence_v2p
print_enstrophy calls release_block, curl
reorder_cuda calls release_block
run calls release_block, compute_derived_fields, pressure_correction, update_stats, compute_pressure_vert, handle_io_step
scalar_product_omp calls release_block, get_field_data
set_field_data calls release_block
set_init calls release_block, set_field_data
transeq_cuda_dist calls release_block
transeq_default calls release_block, transeq_species
transeq_lowmem calls release_block, transeq_species
transeq_omp_dist calls release_block
transeq_species calls release_block
transeq_species_cuda calls release_block
transeq_species_omp calls release_block
compute_pressure_vert calls interpl_c2v
divergence_v2p calls divergence_v2c
gradient_p2v calls gradient_c2v
initial_conditions_tgv calls set_init
postprocess_channel calls print_div_max_mean, print_enstrophy
postprocess_cylinder calls print_div_max_mean, print_enstrophy
postprocess_generic calls print_div_max_mean, print_enstrophy
postprocess_tgv calls print_div_max_mean, print_enstrophy
setup_field_arrays calls get_field_data
transeq_x_cuda calls transeq_cuda_dist
transeq_x_omp calls transeq_omp_dist
transeq_y_cuda calls transeq_cuda_dist
transeq_y_omp calls transeq_omp_dist
transeq_z_cuda calls transeq_cuda_dist
transeq_z_omp calls transeq_omp_dist
xcompact calls run
case_init calls handle_restart
case_channel_init calls case_init
case_cylinder_init calls case_init
case_generic_init calls case_init
case_tgv_init calls case_init
case_channel_t calls case_channel_init
case_cylinder_t calls case_cylinder_init
case_generic_t calls case_generic_init
case_tgv_t calls case_tgv_init