reorder_omp – x3d2
reorder_omp Subroutine
22 statements
Source File
public subroutine reorder_omp(self, u_, u, direction)
Type Bound
omp_backend_t
Arguments
Type Intent Optional Attributes Name
class(omp_backend_t) :: self
class(field_t), intent(inout) :: u_
class(field_t), intent(in) :: u
integer, intent(in) :: direction
Calls
Call graph
reorder_omp calls get_index_reordering, get_padded_dims, get_dirs_from_rdr, set_data_loc
get_index_reordering calls get_index_reordering_dirs, get_index_reordering_rdr
get_index_reordering_dirs calls get_padded_dims, get_index_dir, get_index_ijk, get_sz
get_index_reordering_rdr calls get_index_reordering, get_dirs_from_rdr
get_padded_dims_dir calls get_n_groups
get_padded_dims_phi calls get_padded_dims
get_n_groups_phi calls get_n_groups