reorder_cuda – x3d2
reorder_cuda Subroutine
93 statements
Source File
public subroutine reorder_cuda(self, u_o, u_i, direction)
Type Bound
cuda_backend_t
Arguments
Type Intent Optional Attributes Name
class(cuda_backend_t) :: self
class(field_t), intent(inout) :: u_o
class(field_t), intent(in) :: u_i
integer, intent(in) :: direction
Calls
Call graph
reorder_cuda calls dim3, get_padded_dims, get_block, release_block, reorder_c2x, reorder_x2c, reorder_x2y, reorder_x2z, reorder_y2x, reorder_y2z, reorder_z2x, reorder_z2y, resolve_field_t, set_data_loc
get_block calls get_padded_dims, create_block, set_shape
reorder_c2x calls syncthreads
reorder_x2c calls syncthreads
reorder_x2y calls syncthreads
reorder_y2x calls syncthreads
reorder_y2z calls syncthreads
reorder_z2y calls syncthreads
get_padded_dims_dir calls get_n_groups
get_padded_dims_phi calls get_padded_dims
get_n_groups_phi calls get_n_groups