resolve_field_t – x3d2
resolve_field_t Subroutine
8 statements
Source File
public subroutine resolve_field_t(u_dev, u)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(out), device, pointer, dimension(:, :, :) :: u_dev
class(field_t), intent(in) :: u
Called by
Call graph
compute_qcriterion_cuda calls resolve_field_t
compute_vorticity_cuda calls resolve_field_t
field_max_mean_cuda calls resolve_field_t
field_scale_cuda calls resolve_field_t
field_set_face_cuda calls resolve_field_t
field_set_face_from_field_cuda calls resolve_field_t
field_shift_cuda calls resolve_field_t
field_volume_integral_cuda calls resolve_field_t
reorder_cuda calls resolve_field_t
scalar_product_cuda calls resolve_field_t
slice_max_sum_cuda calls resolve_field_t
sum_yintox_cuda calls resolve_field_t
sum_zintox_cuda calls resolve_field_t
tds_solve_dist calls resolve_field_t
transeq_cuda_dist calls resolve_field_t
transeq_species_cuda calls resolve_field_t
vecadd_cuda calls resolve_field_t
veccopy_cuda calls resolve_field_t
vecmult_cuda calls resolve_field_t
tds_solve_cuda calls tds_solve_dist
transeq_x_cuda calls transeq_cuda_dist
transeq_y_cuda calls transeq_cuda_dist
transeq_z_cuda calls transeq_cuda_dist