run – x3d2
run Subroutine
102 statements
Source File
public subroutine run(self)
Runs the solver forwards in time from t=t_0 to t=T, performing postprocessing/IO and reporting diagnostics.
Type Bound
base_case_t
Arguments
Type Intent Optional Attributes Name
class(base_case_t), intent(inout) :: self
Calls
Called by
Call graph
run calls apply_BC, define_BC, forcings, mpi_reduce, mpi_wtime, body, handle_io_step, is_restart, update_stats, postprocess, case_finalise, compute_derived_fields, compute_pressure_vert, get_block, has_output_field, is_root, pressure_correction, release_block
case_finalise calls is_root, finalise
compute_derived_fields calls get_block, release_block, compute_qcriterion, compute_vorticity, reorder, tds_solve
compute_pressure_vert calls get_block, interpl_c2v, vecadd
get_block calls create_block, set_shape
pressure_correction calls get_block, release_block, divergence_v2p, gradient_p2v, vecadd
divergence_v2p calls divergence_v2c
finalise calls finalise
gradient_p2v calls gradient_c2v
interpl_c2v calls get_block, release_block, reorder, tds_solve
cleanup_field_arrays calls release_block
divergence_v2c calls get_block, release_block, reorder, tds_solve, vecadd
get_dims calls get_dims_dataloc
get_field_data calls get_block, release_block, reorder, copy_f_to_data, get_rdr_from_dirs
get_global_dims calls get_dims_dataloc
gradient_c2v calls get_block, release_block, reorder, tds_solve
prepare_field_buffers calls get_dims, get_global_dims, get_output_dimensions
setup_field_arrays calls get_block, is_root, get_field_data
write_single_field_to_buffer calls get_dims, get_global_dims, get_output_dimensions, stride_data_to_buffer
xcompact calls run