scalar_product_omp – x3d2
scalar_product_omp Function
39 statements
Source File
public function scalar_product_omp(self, x, y) result(s)
m_base_backend
Type Bound
omp_backend_t
Arguments
Type Intent Optional Attributes Name
class(omp_backend_t) :: self
class(field_t), intent(in) :: x
class(field_t), intent(in) :: y
Return Value real(kind=dp)
Calls
Call graph
scalar_product_omp calls mpi_allreduce, get_field_dims, get_block, get_field_data, release_block
get_block calls get_padded_dims, create_block, set_shape
get_field_data calls get_block, release_block, copy_f_to_data, get_rdr_from_dirs, reorder
get_field_dims_dir calls get_n, get_n_groups
get_field_dims_phi calls get_field_dims
get_field_dims_phi_dataloc calls get_field_dims
get_padded_dims_dir calls get_n_groups
get_padded_dims_phi calls get_padded_dims
get_n_groups_phi calls get_n_groups
get_n_phi calls get_n