scalar_product_cuda – x3d2
scalar_product_cuda Function
44 statements
Source File
public function scalar_product_cuda(self, x, y) result(s)
m_base_backend
Type Bound
cuda_backend_t
Arguments
Type Intent Optional Attributes Name
class(cuda_backend_t) :: self
class(field_t), intent(in) :: x
class(field_t), intent(in) :: y
Return Value real(kind=dp)
Calls
Call graph
scalar_product_cuda calls dim3, mpi_allreduce, get_padded_dims, get_dims, resolve_field_t, scalar_product
get_dims calls get_dims_dataloc
scalar_product calls atomicadd
get_padded_dims_dir calls get_n_groups
get_padded_dims_phi calls get_padded_dims
get_n_groups_phi calls get_n_groups