sendrecv_fields – x3d2
sendrecv_fields Subroutine
17 statements
Source File
public subroutine sendrecv_fields(f_recv_s, f_recv_e, f_send_s, f_send_e, n_data, nproc, prev, next)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(out), dimension(:, :, :) :: f_recv_s
real(kind=dp), intent(out), dimension(:, :, :) :: f_recv_e
real(kind=dp), intent(in), dimension(:, :, :) :: f_send_s
real(kind=dp), intent(in), dimension(:, :, :) :: f_send_e
integer, intent(in) :: n_data
integer, intent(in) :: nproc
integer, intent(in) :: prev
integer, intent(in) :: next
Calls
Called by
Call graph
sendrecv_fields calls mpi_irecv, mpi_isend, mpi_waitall
exec_dist_tds_compact calls sendrecv_fields
exec_dist_transeq_compact calls sendrecv_fields
tds_solve_dist calls sendrecv_fields, exec_dist_tds_compact
transeq_omp_dist calls sendrecv_fields, exec_dist_transeq_compact
transeq_species_omp calls sendrecv_fields, exec_dist_transeq_compact
tds_solve_omp calls tds_solve_dist
transeq_x_omp calls transeq_omp_dist
transeq_y_omp calls transeq_omp_dist
transeq_z_omp calls transeq_omp_dist