sendrecv_3fields – x3d2
sendrecv_3fields Subroutine
29 statements
Source File
public subroutine sendrecv_3fields(f1_recv_s, f1_recv_e, f2_recv_s, f2_recv_e, f3_recv_s, f3_recv_e, f1_send_s, f1_send_e, f2_send_s, f2_send_e, f3_send_s, f3_send_e, n_data, nproc, prev, next)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(out), device, dimension(:, :, :) :: f1_recv_s
real(kind=dp), intent(out), device, dimension(:, :, :) :: f1_recv_e
real(kind=dp), intent(out), device, dimension(:, :, :) :: f2_recv_s
real(kind=dp), intent(out), device, dimension(:, :, :) :: f2_recv_e
real(kind=dp), intent(out), device, dimension(:, :, :) :: f3_recv_s
real(kind=dp), intent(out), device, dimension(:, :, :) :: f3_recv_e
real(kind=dp), intent(in), device, dimension(:, :, :) :: f1_send_s
real(kind=dp), intent(in), device, dimension(:, :, :) :: f1_send_e
real(kind=dp), intent(in), device, dimension(:, :, :) :: f2_send_s
real(kind=dp), intent(in), device, dimension(:, :, :) :: f2_send_e
real(kind=dp), intent(in), device, dimension(:, :, :) :: f3_send_s
real(kind=dp), intent(in), device, dimension(:, :, :) :: f3_send_e
integer, intent(in) :: n_data
integer, intent(in) :: nproc
integer, intent(in) :: prev
integer, intent(in) :: next
Calls
Called by
Call graph
sendrecv_3fields calls mpi_irecv, mpi_isend, mpi_waitall
exec_dist_transeq_3fused calls sendrecv_3fields
transeq_cuda_dist calls sendrecv_3fields, exec_dist_transeq_3fused
transeq_species_cuda calls exec_dist_transeq_3fused
transeq_x_cuda calls transeq_cuda_dist
transeq_y_cuda calls transeq_cuda_dist
transeq_z_cuda calls transeq_cuda_dist