sendrecv_fields – x3d2
sendrecv_fields Subroutine
17 statements
Source File
public subroutine sendrecv_fields(f_recv_s, f_recv_e, f_send_s, f_send_e, n_data, nproc, prev, next)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(out), device, dimension(:, :, :) :: f_recv_s
real(kind=dp), intent(out), device, dimension(:, :, :) :: f_recv_e
real(kind=dp), intent(in), device, dimension(:, :, :) :: f_send_s
real(kind=dp), intent(in), device, dimension(:, :, :) :: f_send_e
integer, intent(in) :: n_data
integer, intent(in) :: nproc
integer, intent(in) :: prev
integer, intent(in) :: next
Calls
Called by
Call graph
sendrecv_fields calls mpi_irecv, mpi_isend, mpi_waitall
exec_dist_tds_compact calls sendrecv_fields
tds_solve_dist calls sendrecv_fields, exec_dist_tds_compact
transeq_species_cuda calls sendrecv_fields
tds_solve_cuda calls tds_solve_dist