set_init – x3d2
set_init Subroutine
28 statements
Source File
public subroutine set_init(self, field, field_func)
Type Bound
base_case_t
Arguments
Type Intent Optional Attributes Name
class(base_case_t) :: self
class(field_t), intent(inout) :: field
public pure function field_func(coords) result(r)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: coords(3)
Return Value real(kind=dp)
Calls
Called by
Call graph
set_init calls get_block, get_coordinates, get_dims, release_block, set_field_data
get_block calls get_padded_dims, create_block, set_shape
get_dims calls get_dims_dataloc
set_field_data calls get_block, release_block, copy_data_to_f, get_rdr_from_dirs, reorder
get_padded_dims_dir calls get_n_groups
get_padded_dims_phi calls get_padded_dims
get_n_groups_phi calls get_n_groups
initial_conditions_tgv calls set_init