set_padded_dims – x3d2
set_padded_dims Subroutine
5 statements
Source File
public subroutine set_padded_dims(self, vert_dims)
Type Bound
mesh_t
Arguments
Type Intent Optional Attributes Name
class(mesh_t), intent(inout) :: self
integer, intent(in), dimension(3) :: vert_dims
Called by
Call graph
compute_padded_dims calls set_padded_dims
allocator_init calls compute_padded_dims
allocator_t calls allocator_init