set_field_data – x3d2
set_field_data Subroutine
23 statements
Source File
public subroutine set_field_data(self, f, data, dir)
Type Bound
base_backend_t
Arguments
Type Intent Optional Attributes Name
class(base_backend_t) :: self
class(field_t), intent(inout) :: f
Field
real(kind=dp), intent(in), dimension(:, :, :) :: data
Input array
integer, intent(in), optional :: dir
Orientation of input array (defaults to Cartesian)
Calls
Called by
Call graph
set_field_data calls copy_data_to_f, get_block, get_rdr_from_dirs, release_block, reorder
get_block calls create_block, set_shape
define_bc_channel calls set_field_data
define_bc_cylinder calls set_field_data
initial_conditions_channel calls set_field_data
initial_conditions_cylinder calls set_field_data
set_init calls set_field_data
initial_conditions_tgv calls set_init
case_init calls handle_restart
case_channel_init calls case_init
case_cylinder_init calls case_init
case_generic_init calls case_init
case_tgv_init calls case_init
case_channel_t calls case_channel_init
case_cylinder_t calls case_cylinder_init
case_generic_t calls case_generic_init
case_tgv_t calls case_tgv_init