set_data_loc – x3d2
set_data_loc Subroutine
5 statements
Source File
public subroutine set_data_loc(self, data_loc)
Type Bound
field_t
Arguments
Type Intent Optional Attributes Name
class(field_t) :: self
integer, intent(in) :: data_loc
Called by
Call graph
define_bc_channel calls set_data_loc
define_bc_cylinder calls set_data_loc
initial_conditions_channel calls set_data_loc
initial_conditions_cylinder calls set_data_loc
initial_conditions_generic calls set_data_loc
initial_conditions_tgv calls set_data_loc
reorder_cuda calls set_data_loc
reorder_omp calls set_data_loc
tds_solve_cuda calls set_data_loc
tds_solve_omp calls set_data_loc
transeq_cuda_dist calls set_data_loc
transeq_omp_dist calls set_data_loc
transeq_species_cuda calls set_data_loc
transeq_species_omp calls set_data_loc
transeq_x_cuda calls transeq_cuda_dist
transeq_x_omp calls transeq_omp_dist
transeq_y_cuda calls transeq_cuda_dist
transeq_y_omp calls transeq_omp_dist
transeq_z_cuda calls transeq_cuda_dist
transeq_z_omp calls transeq_omp_dist
case_init calls handle_restart
case_channel_init calls case_init
case_cylinder_init calls case_init
case_generic_init calls case_init
case_tgv_init calls case_init
case_channel_t calls case_channel_init
case_cylinder_t calls case_cylinder_init
case_generic_t calls case_generic_init
case_tgv_t calls case_tgv_init