setup_field_arrays – x3d2
setup_field_arrays Subroutine
29 statements
Source File
public subroutine setup_field_arrays(solver, field_names, field_ptrs, host_fields)
Arguments
Type Intent Optional Attributes Name
class(solver_t), intent(in) :: solver
character(len=*), intent(in), dimension(:) :: field_names
type(field_ptr_t), intent(out), allocatable :: field_ptrs(:)
type(field_ptr_t), intent(out), allocatable :: host_fields(:)
Calls
Called by
Call graph
setup_field_arrays calls get_block, get_field_data, is_root
get_block calls create_block, set_shape
get_field_data calls get_block, copy_f_to_data, get_rdr_from_dirs, release_block, reorder
run calls handle_io_step
xcompact calls run