slice_max_sum_cuda – x3d2
slice_max_sum_cuda Subroutine
52 statements
Source File
public subroutine slice_max_sum_cuda(self, max_val, sum_val, f, i_slice, enforced_data_loc)
m_base_backend
Type Bound
cuda_backend_t
Arguments
Type Intent Optional Attributes Name
class(cuda_backend_t) :: self
real(kind=dp), intent(out) :: max_val
real(kind=dp), intent(out) :: sum_val
class(field_t), intent(in) :: f
integer, intent(in) :: i_slice
integer, intent(in), optional :: enforced_data_loc
Calls
Call graph
slice_max_sum_cuda calls dim3, get_dims, get_padded_dims, resolve_field_t, slice_max_sum_kernel
get_dims calls get_dims_dataloc
slice_max_sum_kernel calls atomicadd, atomicmax