stretching_matrix – x3d2
stretching_matrix Subroutine
260 statements
Source File
public subroutine stretching_matrix(self, geo, xdirps, ydirps, zdirps)
Stretching necessitates a special operation in spectral space. The coefficients for the operation are stored in matrix form.
Ref. JCP 228 (2009), 5989–6015, Sec 5
Type Bound
poisson_fft_t
Arguments
Type Intent Optional Attributes Name
class(poisson_fft_t) :: self
type(geo_t), intent(in) :: geo
type(dirps_t), intent(in) :: xdirps
type(dirps_t), intent(in) :: ydirps
type(dirps_t), intent(in) :: zdirps
Calls
Called by
Call graph
stretching_matrix calls get_imag, get_km, get_km_im, get_km_re, get_real
get_km calls get_imag, get_real
get_km_im calls get_imag, get_km
get_km_re calls get_km, get_real
base_init calls stretching_matrix