stride_data_to_buffer – x3d2
stride_data_to_buffer Subroutine
38 statements
Source File
public subroutine stride_data_to_buffer(input_data, dims, stride, out_buffer, output_dims_out)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in), dimension(:, :, :) :: input_data
integer, intent(in), dimension(3) :: dims
integer, intent(in), dimension(3) :: stride
real(kind=dp), intent(inout), dimension(:, :, :), allocatable :: out_buffer
integer, intent(out), dimension(3) :: output_dims_out
Called by
Call graph
write_single_field_to_buffer calls stride_data_to_buffer
run calls handle_io_step
xcompact calls run