sum_yintox_omp – x3d2
sum_yintox_omp Subroutine
7 statements
Source File
public subroutine sum_yintox_omp(self, u, u_)
Type Bound
omp_backend_t
Arguments
Type Intent Optional Attributes Name
class(omp_backend_t) :: self
class(field_t), intent(inout) :: u
class(field_t), intent(in) :: u_
Calls
Call graph
sum_yintox_omp calls sum_intox_omp
sum_intox_omp calls get_index_reordering, get_padded_dims
get_index_reordering calls get_index_dir, get_index_ijk