sum_intox_omp – x3d2
sum_intox_omp Subroutine
20 statements
Source File
public subroutine sum_intox_omp(self, u, u_, dir_to)
Arguments
Type Intent Optional Attributes Name
class(omp_backend_t) :: self
class(field_t), intent(inout) :: u
class(field_t), intent(in) :: u_
integer, intent(in) :: dir_to
Calls
Called by
Call graph
sum_intox_omp calls get_index_reordering, get_padded_dims
get_index_reordering calls get_index_reordering_dirs, get_index_reordering_rdr
get_index_reordering_dirs calls get_padded_dims, get_index_dir, get_index_ijk, get_sz
get_index_reordering_rdr calls get_index_reordering, get_dirs_from_rdr
get_padded_dims_dir calls get_n_groups
get_padded_dims_phi calls get_padded_dims
get_n_groups_phi calls get_n_groups
sum_yintox_omp calls sum_intox_omp
sum_zintox_omp calls sum_intox_omp