sum_yintox_cuda – x3d2
sum_yintox_cuda Subroutine
15 statements
Source File
public subroutine sum_yintox_cuda(self, u, u_y)
Type Bound
cuda_backend_t
Arguments
Type Intent Optional Attributes Name
class(cuda_backend_t) :: self
class(field_t), intent(inout) :: u
class(field_t), intent(in) :: u_y
Calls
Call graph
sum_yintox_cuda calls dim3, get_padded_dims, resolve_field_t, sum_yintox
sum_yintox calls syncthreads
get_padded_dims_dir calls get_n_groups
get_padded_dims_phi calls get_padded_dims
get_n_groups_phi calls get_n_groups