sum_zintox_omp – x3d2
sum_zintox_omp Subroutine
7 statements
Source File
public subroutine sum_zintox_omp(self, u, u_)
Type Bound
omp_backend_t
Arguments
Type Intent Optional Attributes Name
class(omp_backend_t) :: self
class(field_t), intent(inout) :: u
class(field_t), intent(in) :: u_
Calls
Call graph
sum_zintox_omp calls sum_intox_omp
sum_intox_omp calls get_index_reordering, get_padded_dims
get_index_reordering calls get_index_reordering_dirs, get_index_reordering_rdr
get_index_reordering_dirs calls get_padded_dims, get_index_dir, get_index_ijk, get_sz
get_index_reordering_rdr calls get_index_reordering, get_dirs_from_rdr
get_padded_dims_dir calls get_n_groups
get_padded_dims_phi calls get_padded_dims
get_n_groups_phi calls get_n_groups