tds_solve_cuda – x3d2
tds_solve_cuda Subroutine
17 statements
Source File
public subroutine tds_solve_cuda(self, du, u, tdsops)
Type Bound
cuda_backend_t
Arguments
Type Intent Optional Attributes Name
class(cuda_backend_t) :: self
class(field_t), intent(inout) :: du
class(field_t), intent(in) :: u
class(tdsops_t), intent(in) :: tdsops
Calls
Call graph
tds_solve_cuda calls dim3, get_n_groups, move_data_loc, set_data_loc, tds_solve_dist
tds_solve_dist calls get_n_groups, copy_into_buffers, exec_dist_tds_compact, resolve_field_t, sendrecv_fields
copy_into_buffers calls dim3, buffer_copy
exec_dist_tds_compact calls sendrecv_fields, der_univ_dist, der_univ_subs
get_n_groups_phi calls get_n_groups
sendrecv_fields calls mpi_irecv, mpi_isend, mpi_waitall