tds_solve_omp – x3d2
tds_solve_omp Subroutine
14 statements
Source File
public subroutine tds_solve_omp(self, du, u, tdsops)
Type Bound
omp_backend_t
Arguments
Type Intent Optional Attributes Name
class(omp_backend_t) :: self
class(field_t), intent(inout) :: du
class(field_t), intent(in) :: u
class(tdsops_t), intent(in) :: tdsops
Calls
Call graph
tds_solve_omp calls move_data_loc, set_data_loc, tds_solve_dist
tds_solve_dist calls get_n_groups, copy_into_buffers, exec_dist_tds_compact, sendrecv_fields
exec_dist_tds_compact calls sendrecv_fields, der_univ_dist, der_univ_subs
sendrecv_fields calls mpi_irecv, mpi_isend, mpi_waitall
get_n_groups_phi calls get_n_groups