tds_solve_dist – x3d2
tds_solve_dist Subroutine
23 statements
Source File
public subroutine tds_solve_dist(self, du, u, tdsops, blocks, threads)
Type Bound
cuda_backend_t
Arguments
Type Intent Optional Attributes Name
class(cuda_backend_t) :: self
class(field_t), intent(inout) :: du
class(field_t), intent(in) :: u
class(tdsops_t), intent(in) :: tdsops
type(dim3), intent(in) :: blocks
type(dim3), intent(in) :: threads
Calls
Called by
Call graph
tds_solve_dist calls get_n_groups, copy_into_buffers, exec_dist_tds_compact, resolve_field_t, sendrecv_fields
copy_into_buffers calls dim3, buffer_copy
exec_dist_tds_compact calls sendrecv_fields, der_univ_dist, der_univ_subs
sendrecv_fields calls mpi_irecv, mpi_isend, mpi_waitall
get_n_groups_phi calls get_n_groups
tds_solve_cuda calls tds_solve_dist