tdsops_init – x3d2
tdsops_init Function
82 statements
Source File
public function tdsops_init(n_tds, delta, operation, scheme, bc_start, bc_end, stretch, stretch_correct, n_halo, from_to, sym, c_nu, nu0_nu) result(tdsops)
Constructor function for the tdsops_t class.
'n_tds', 'delta', 'operation', 'scheme', 'bc_start', and 'bc_end' are necessary arguments. The remaining arguments are optional.
'stretch' is for obtaining the correct derivations in a stretched mesh 'stretch_correct' is for correcting the second derivative with the first
'from_to' is necessary for interpolation and staggared derivative, and it can be 'v2p' or 'p2v'. If the specific region the instance is operating is not a boundary region, then 'bc_start' and 'bc_end' are BC_HALO.
'sym' is relevant when the BC is free-slip. If sym is .true. then it means the field we operate on is assumed to be an even function (symmetric, cos type) accross the boundary. If it is .false. it means the field is assumed to be an odd function (anti-symmetric, sin type).
'c_nu', 'nu0_nu' are relevant when operation is second order derivative and scheme is compact6-hyperviscous.
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: n_tds
Tridiagonal system size
real(kind=dp), intent(in) :: delta
Grid spacing
character(len=*), intent(in) :: operation
character(len=*), intent(in) :: scheme
integer, intent(in) :: bc_start
Boundary Cond.
integer, intent(in) :: bc_end
Boundary Cond.
real(kind=dp), intent(in), optional :: stretch(:)
Stretching coefficients
real(kind=dp), intent(in), optional :: stretch_correct(:)
Stretch correction
integer, intent(in), optional :: n_halo
Number of halo cells
character(len=*), intent(in), optional :: from_to
'v2p' or 'p2v'
logical, intent(in), optional :: sym
(==npaire), only for Neumann BCs
real(kind=dp), intent(in), optional :: c_nu
params for hypervisc.
real(kind=dp), intent(in), optional :: nu0_nu
params for hypervisc.
Return Value type(tdsops_t)
return value of the function
Calls
Called by
Call graph
tdsops_init calls deriv_1st, deriv_2nd, interpl_mid, stagder_1st
deriv_1st calls preprocess_dist, preprocess_thom
deriv_2nd calls preprocess_dist, preprocess_thom
interpl_mid calls preprocess_dist, preprocess_thom
stagder_1st calls preprocess_dist, preprocess_thom
tdsops_t calls tdsops_init
cuda_tdsops_init calls tdsops_init
cuda_tdsops_t calls cuda_tdsops_init