transeq_species – x3d2
transeq_species Subroutine
38 statements
Source File
public subroutine transeq_species(self, rhs, variables)
Skew-symmetric form of convection-diffusion terms in the species equation. Inputs from velocity grid and outputs to velocity grid.
Type Bound
solver_t
Arguments
Type Intent Optional Attributes Name
class(solver_t) :: self
type(flist_t), intent(inout) :: rhs(:)
type(flist_t), intent(in) :: variables(:)
Calls
Called by
Call graph
transeq_species calls get_block, release_block, reorder, sum_yintox, sum_zintox, transeq_species
get_block calls create_block, set_shape
transeq_default calls transeq_species
transeq_lowmem calls transeq_species