transeq_omp_dist – x3d2
transeq_omp_dist Subroutine
11 statements
Source File
public subroutine transeq_omp_dist(self, du, dv, dw, u, v, w, dirps)
Type Bound
omp_backend_t
Arguments
Type Intent Optional Attributes Name
class(omp_backend_t) :: self
class(field_t), intent(inout) :: du
class(field_t), intent(inout) :: dv
class(field_t), intent(inout) :: dw
class(field_t), intent(in) :: u
class(field_t), intent(in) :: v
class(field_t), intent(in) :: w
type(dirps_t), intent(in) :: dirps
Calls
Called by
Call graph
transeq_omp_dist calls get_n, get_n_groups, copy_into_buffers, exec_dist_transeq_compact, get_block, release_block, sendrecv_fields, set_data_loc
exec_dist_transeq_compact calls sendrecv_fields, der_univ_dist, der_univ_fused_subs
get_block calls get_padded_dims, create_block, set_shape
sendrecv_fields calls mpi_irecv, mpi_isend, mpi_waitall
get_n_groups_phi calls get_n_groups
get_n_phi calls get_n
get_padded_dims_dir calls get_n_groups
get_padded_dims_phi calls get_padded_dims
transeq_x_omp calls transeq_omp_dist
transeq_y_omp calls transeq_omp_dist
transeq_z_omp calls transeq_omp_dist