transeq_lowmem – x3d2
transeq_lowmem Subroutine
70 statements
Source File
public subroutine transeq_lowmem(self, rhs, variables)
low memory version of the transport equation, roughly %2 slower overall
Arguments
Type Intent Optional Attributes Name
class(solver_t) :: self
type(flist_t), intent(inout) :: rhs(:)
type(flist_t), intent(inout) :: variables(:)
Calls
Call graph
transeq_lowmem calls get_block, release_block, transeq_species, reorder, sum_yintox, sum_zintox, transeq_x, transeq_y, transeq_z
get_block calls create_block, set_shape
transeq_species calls get_block, release_block, reorder, sum_yintox, sum_zintox, transeq_species