transeq_3fused_dist – x3d2
transeq_3fused_dist Subroutine
156 statements
Source File
public subroutine transeq_3fused_dist(du, dud, d2u, send_du_s, send_du_e, send_dud_s, send_dud_e, send_d2u_s, send_d2u_e, u, u_s, u_e, v, v_s, v_e, n_tds, n_rhs, d1_coeffs_s, d1_coeffs_e, d1_coeffs, d1_fw, d1_bw, d1_af, d2_coeffs_s, d2_coeffs_e, d2_coeffs, d2_fw, d2_bw, d2_af)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(out), device, dimension(:, :, :) :: du
real(kind=dp), intent(out), device, dimension(:, :, :) :: dud
real(kind=dp), intent(out), device, dimension(:, :, :) :: d2u
real(kind=dp), intent(out), device, dimension(:, :, :) :: send_du_s
real(kind=dp), intent(out), device, dimension(:, :, :) :: send_du_e
real(kind=dp), intent(out), device, dimension(:, :, :) :: send_dud_s
real(kind=dp), intent(out), device, dimension(:, :, :) :: send_dud_e
real(kind=dp), intent(out), device, dimension(:, :, :) :: send_d2u_s
real(kind=dp), intent(out), device, dimension(:, :, :) :: send_d2u_e
real(kind=dp), intent(in), device, dimension(:, :, :) :: u
real(kind=dp), intent(in), device, dimension(:, :, :) :: u_s
real(kind=dp), intent(in), device, dimension(:, :, :) :: u_e
real(kind=dp), intent(in), device, dimension(:, :, :) :: v
real(kind=dp), intent(in), device, dimension(:, :, :) :: v_s
real(kind=dp), intent(in), device, dimension(:, :, :) :: v_e
integer, intent(in), value :: n_tds
integer, intent(in), value :: n_rhs
real(kind=dp), intent(in), device :: d1_coeffs_s(:,:)
real(kind=dp), intent(in), device :: d1_coeffs_e(:,:)
real(kind=dp), intent(in), device :: d1_coeffs(:)
real(kind=dp), intent(in), device :: d1_fw(:)
real(kind=dp), intent(in), device :: d1_bw(:)
real(kind=dp), intent(in), device :: d1_af(:)
real(kind=dp), intent(in), device :: d2_coeffs_s(:,:)
real(kind=dp), intent(in), device :: d2_coeffs_e(:,:)
real(kind=dp), intent(in), device :: d2_coeffs(:)
real(kind=dp), intent(in), device :: d2_fw(:)
real(kind=dp), intent(in), device :: d2_bw(:)
real(kind=dp), intent(in), device :: d2_af(:)
Called by
Call graph
exec_dist_transeq_3fused calls transeq_3fused_dist
transeq_cuda_dist calls exec_dist_transeq_3fused
transeq_x_cuda calls transeq_cuda_dist
transeq_y_cuda calls transeq_cuda_dist
transeq_z_cuda calls transeq_cuda_dist