transeq_species_cuda – x3d2
transeq_species_cuda Subroutine
40 statements
Source File
public subroutine transeq_species_cuda(self, dspec, uvw, spec, nu, dirps, sync)
Compute the convection and diffusion for the given field in the given direction. Halo exchange for the given field is necessary When sync is true, halo exchange of momentum is necessary
Type Bound
cuda_backend_t
Arguments
Type Intent Optional Attributes Name
class(cuda_backend_t) :: self
class(field_t), intent(inout) :: dspec
class(field_t), intent(in) :: uvw
class(field_t), intent(in) :: spec
real(kind=dp), intent(in) :: nu
type(dirps_t), intent(in) :: dirps
logical, intent(in) :: sync
Calls
Call graph
transeq_species_cuda calls get_n, get_n_groups, copy_into_buffers, exec_dist_transeq_3fused, get_block, release_block, resolve_field_t, sendrecv_fields, set_data_loc
copy_into_buffers calls dim3, buffer_copy
exec_dist_transeq_3fused calls sendrecv_3fields, transeq_3fused_dist, transeq_3fused_subs
get_block calls get_padded_dims, create_block, set_shape
sendrecv_fields calls mpi_irecv, mpi_isend, mpi_waitall
get_n_groups_phi calls get_n_groups
get_n_phi calls get_n
sendrecv_3fields calls mpi_irecv, mpi_isend, mpi_waitall
get_padded_dims_dir calls get_n_groups
get_padded_dims_phi calls get_padded_dims