transeq_default – x3d2
transeq_default Subroutine
55 statements
Source File
public subroutine transeq_default(self, rhs, variables)
Skew-symmetric form of convection-diffusion terms in the incompressible Navier-Stokes momemtum equations, excluding pressure terms. Inputs from velocity grid and outputs to velocity grid.
Arguments
Type Intent Optional Attributes Name
class(solver_t) :: self
type(flist_t), intent(inout) :: rhs(:)
type(flist_t), intent(inout) :: variables(:)
Calls
Call graph
transeq_default calls get_block, release_block, transeq_species, reorder, sum_yintox, sum_zintox, transeq_x, transeq_y, transeq_z
get_block calls create_block, set_shape
transeq_species calls get_block, release_block, reorder, sum_yintox, sum_zintox, transeq_species