transeq_cuda_dist – x3d2
transeq_cuda_dist Subroutine
39 statements
Source File
public subroutine transeq_cuda_dist(self, du, dv, dw, u, v, w, dirps, blocks, threads)
Type Bound
cuda_backend_t
Arguments
Type Intent Optional Attributes Name
class(cuda_backend_t) :: self
class(field_t), intent(inout) :: du
class(field_t), intent(inout) :: dv
class(field_t), intent(inout) :: dw
class(field_t), intent(in) :: u
class(field_t), intent(in) :: v
class(field_t), intent(in) :: w
type(dirps_t), intent(in) :: dirps
type(dim3), intent(in) :: blocks
type(dim3), intent(in) :: threads
Calls
Called by
Call graph
transeq_cuda_dist calls get_n, get_n_groups, copy_into_buffers, exec_dist_transeq_3fused, get_block, release_block, resolve_field_t, sendrecv_3fields, set_data_loc
copy_into_buffers calls dim3, buffer_copy
exec_dist_transeq_3fused calls sendrecv_3fields, transeq_3fused_dist, transeq_3fused_subs
get_block calls get_padded_dims, create_block, set_shape
sendrecv_3fields calls mpi_irecv, mpi_isend, mpi_waitall
get_n_groups_phi calls get_n_groups
get_n_phi calls get_n
get_padded_dims_dir calls get_n_groups
get_padded_dims_phi calls get_padded_dims
transeq_x_cuda calls transeq_cuda_dist
transeq_y_cuda calls transeq_cuda_dist
transeq_z_cuda calls transeq_cuda_dist