transeq – x3d2
transeq Subroutine
46 statements
Source File
public subroutine transeq(self, du, dv, dw, u, v, w)
Skew-symmetric form of convection-diffusion terms in the incompressible Navier-Stokes momemtum equations, excluding pressure terms. Inputs from velocity grid and outputs to velocity grid.
Type Bound
solver_t
Arguments
Type Intent Optional Attributes Name
class(solver_t) :: self
class(field_t), intent(inout) :: du
class(field_t), intent(inout) :: dv
class(field_t), intent(inout) :: dw
class(field_t), intent(in) :: u
class(field_t), intent(in) :: v
class(field_t), intent(in) :: w
Calls
Called by
Call graph
transeq calls get_block, release_block, reorder, sum_yintox, sum_zintox, transeq_x, transeq_y, transeq_z
get_block calls get_padded_dims, create_block, set_shape
get_padded_dims_dir calls get_n_groups
get_padded_dims_phi calls get_padded_dims
get_n_groups_phi calls get_n_groups
run calls transeq
xcompact calls run