vecadd_omp – x3d2
vecadd_omp Subroutine
29 statements
Source File
public subroutine vecadd_omp(self, a, x, b, y)
Type Bound
omp_backend_t
Arguments
Type Intent Optional Attributes Name
class(omp_backend_t) :: self
real(kind=dp), intent(in) :: a
class(field_t), intent(in) :: x
real(kind=dp), intent(in) :: b
class(field_t), intent(inout) :: y
Calls
Call graph
vecadd_omp calls get_padded_dims
get_padded_dims_dir calls get_n_groups
get_padded_dims_phi calls get_padded_dims
get_n_groups_phi calls get_n_groups