write_single_field_to_buffer – x3d2
write_single_field_to_buffer Subroutine
34 statements
Source File
public subroutine write_single_field_to_buffer(field_name, host_field, solver, stride_factors, data_loc, field_buffers, last_shape_dims, last_stride_factors, last_output_shape)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: field_name
class(field_t), pointer :: host_field
class(solver_t), intent(in) :: solver
integer, intent(in), dimension(3) :: stride_factors
integer, intent(in) :: data_loc
type(field_buffer_map_t), intent(inout) :: field_buffers(:)
integer(kind=i8), intent(inout), dimension(3) :: last_shape_dims
integer, intent(inout), dimension(3) :: last_stride_factors
integer(kind=i8), intent(inout), dimension(3) :: last_output_shape
Calls
Called by
Call graph
write_single_field_to_buffer calls get_dims, get_global_dims, get_output_dimensions, stride_data_to_buffer
get_dims calls get_dims_dataloc
get_global_dims calls get_dims_dataloc
run calls handle_io_step
xcompact calls run