allocator_t – x3d2
allocator_t Interface
3 statements
Source File
public interface allocator_t
Calls
Module Procedures
public function allocator_init(mesh, sz) result(allocator)
Arguments
Type Intent Optional Attributes Name
type(mesh_t), intent(inout), target :: mesh
integer, intent(in) :: sz
Return Value type(allocator_t)
Call graph
allocator_t calls allocator_init
allocator_init calls get_padded_dims, compute_padded_dims
compute_padded_dims calls get_dims, set_padded_dims, set_sz
get_dims calls get_dims_dataloc
get_padded_dims_dir calls get_n_groups
get_padded_dims_phi calls get_padded_dims
get_n_groups_phi calls get_n_groups