case_generic_t – x3d2
case_generic_t Interface
3 statements
Source File
public interface case_generic_t
Calls
Module Procedures
public function case_generic_init(backend, mesh, host_allocator) result(flow_case)
Arguments
Type Intent Optional Attributes Name
class(base_backend_t), intent(inout), target :: backend
type(mesh_t), intent(inout), target :: mesh
type(allocator_t), intent(inout), target :: host_allocator
Return Value type(case_generic_t)
Call graph
case_generic_t calls case_generic_init
case_generic_init calls case_init
case_init calls initial_conditions, handle_restart, is_restart, has_output_field, init
init calls init_poisson_fft, allocate_tdsops, get_argument, get_block, get_global_dims, is_root
allocate_tdsops calls alloc_tdsops, get_n
get_block calls create_block, set_shape
get_global_dims calls get_dims_dataloc
get_dims calls get_dims_dataloc
set_field_data calls get_block, copy_data_to_f, get_rdr_from_dirs, release_block, reorder
get_n_phi calls get_n