cuda_tdsops_t – x3d2
cuda_tdsops_t Interface
3 statements
Source File
public interface cuda_tdsops_t
Calls
Module Procedures
public function cuda_tdsops_init(n_tds, delta, operation, scheme, bc_start, bc_end, stretch, stretch_correct, n_halo, from_to, sym, c_nu, nu0_nu) result(tdsops)
Constructor function for the cuda_tdsops_t class. See tdsops_t for details.
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: n_tds
real(kind=dp), intent(in) :: delta
character(len=*), intent(in) :: operation
character(len=*), intent(in) :: scheme
integer, intent(in) :: bc_start
integer, intent(in) :: bc_end
real(kind=dp), intent(in), optional :: stretch(:)
real(kind=dp), intent(in), optional :: stretch_correct(:)
integer, intent(in), optional :: n_halo
character(len=*), intent(in), optional :: from_to
logical, intent(in), optional :: sym
real(kind=dp), intent(in), optional :: c_nu
real(kind=dp), intent(in), optional :: nu0_nu
Return Value type(cuda_tdsops_t)
return value of the function
Call graph
cuda_tdsops_t calls cuda_tdsops_init
cuda_tdsops_init calls tdsops_init
tdsops_init calls deriv_1st, deriv_2nd, interpl_mid, stagder_1st
deriv_1st calls preprocess_dist, preprocess_penta_dist, preprocess_thom
deriv_2nd calls preprocess_dist, preprocess_thom
interpl_mid calls preprocess_dist, preprocess_thom
stagder_1st calls preprocess_dist, preprocess_thom