get_index_reordering – x3d2
get_index_reordering Interface
3 statements
Source File
public interface get_index_reordering
Calls
Called by
Module Procedures
public pure subroutine get_index_reordering_rdr(out_i, out_j, out_k, in_i, in_j, in_k, reorder_dir, mesh)
Arguments
Type Intent Optional Attributes Name
integer, intent(out) :: out_i
integer, intent(out) :: out_j
integer, intent(out) :: out_k
integer, intent(in) :: in_i
integer, intent(in) :: in_j
integer, intent(in) :: in_k
integer, intent(in) :: reorder_dir
type(mesh_t), intent(in) :: mesh
public pure subroutine get_index_reordering_dirs(out_i, out_j, out_k, in_i, in_j, in_k, dir_from, dir_to, mesh)
Converts a set of application storage directional index to an other direction. The two directions are defined by the reorder_dir variable, RDR_X2Y will go from storage in X to Y etc.
Arguments
Type Intent Optional Attributes Name
integer, intent(out) :: out_i
integer, intent(out) :: out_j
integer, intent(out) :: out_k
integer, intent(in) :: in_i
integer, intent(in) :: in_j
integer, intent(in) :: in_k
integer, intent(in) :: dir_from
integer, intent(in) :: dir_to
type(mesh_t), intent(in) :: mesh
Call graph
get_index_reordering calls get_index_reordering_dirs, get_index_reordering_rdr
get_index_reordering_dirs calls get_padded_dims, get_index_dir, get_index_ijk, get_sz
get_index_reordering_rdr calls get_index_reordering, get_dirs_from_rdr
get_padded_dims_dir calls get_n_groups
get_padded_dims_phi calls get_padded_dims
get_n_groups_phi calls get_n_groups
reorder_omp calls get_index_reordering
sum_intox_omp calls get_index_reordering
sum_yintox_omp calls sum_intox_omp
sum_zintox_omp calls sum_intox_omp