mesh_t – x3d2
mesh_t Interface
3 statements
Source File
public interface mesh_t
Calls
Module Procedures
public function mesh_init(dims_global, nproc_dir, L_global, BC_x, BC_y, BC_z, stretching, beta, use_2decomp) result(mesh)
Completely initialise the mesh object. Upon initialisation the mesh object can be read-only and shouldn't be edited Takes as argument global information about the mesh like its length, number of cells and decomposition in each direction
Arguments
Type Intent Optional Attributes Name
integer, intent(in), dimension(3) :: dims_global
integer, intent(in), dimension(3) :: nproc_dir
real(kind=dp), intent(in), dimension(3) :: L_global
character(len=*), intent(in), dimension(2) :: BC_x
character(len=*), intent(in), dimension(2) :: BC_y
character(len=*), intent(in), dimension(2) :: BC_z
character(len=*), intent(in), optional, dimension(3) :: stretching
real(kind=dp), intent(in), optional, dimension(3) :: beta
logical, intent(in), optional :: use_2decomp
Return Value class(mesh_t), allocatable
Call graph
mesh_t calls mesh_init
mesh_init calls mpi_comm_rank, mpi_comm_size, decomposition_2decomp, decomposition_generic, is_avail_2decomp, obtain_coordinates
decomposition_2decomp calls mpi_comm_rank, decomp_2d_init, mpi_allreduce, mpi_cart_coords, compute_rank_pos_from_global, copy_vert2cell_dims, is_root, xsize, xstart
decomposition_generic calls compute_rank_pos_from_global, copy_vert2cell_dims, is_root