solver_t – x3d2
solver_t Interface
3 statements
Source File
public interface solver_t
Calls
Module Procedures
public function init(backend, mesh, host_allocator) result(solver)
Arguments
Type Intent Optional Attributes Name
class(base_backend_t), intent(inout), target :: backend
type(mesh_t), intent(inout), target :: mesh
type(allocator_t), intent(inout), target :: host_allocator
Return Value type(solver_t)
Call graph
solver_t calls init
init calls init_poisson_fft, allocate_tdsops, get_argument, get_block, get_global_dims, is_root
allocate_tdsops calls alloc_tdsops, get_n
get_block calls get_padded_dims, create_block, set_shape
get_global_dims calls get_dims_dataloc
get_n_phi calls get_n
get_padded_dims_dir calls get_n_groups
get_padded_dims_phi calls get_padded_dims
get_n_groups_phi calls get_n_groups