xcompact – x3d2
xcompact Program
90 statements
Source File
Uses
m_allocator
m_cuda_common
m_config
m_case_channel
m_case_generic
m_cuda_allocator
m_omp_backend
m_base_backend
m_case_cylinder
m_omp_common
m_mesh
m_base_case
m_case_tgv
m_cuda_backend
mpi
m_common
Calls
Variables
Type Attributes Name Initial
class(base_backend_t), pointer :: backend
class(allocator_t), pointer :: allocator
type(allocator_t), pointer :: host_allocator
type(mesh_t), target :: mesh
class(base_case_t), allocatable :: flow_case
type(cuda_backend_t), target :: cuda_backend
type(cuda_allocator_t), target :: cuda_allocator
integer :: ndevs
integer :: devnum
type(omp_backend_t), target :: omp_backend
type(allocator_t), target :: omp_allocator
type(domain_config_t) :: domain_cfg
type(solver_config_t) :: solver_cfg
character(len=32) :: backend_name
integer :: dims(3)
integer :: nrank
integer :: nproc
integer :: ierr
logical :: use_2decomp
Call graph
xcompact calls cudagetdevice, cudagetdevicecount, cudasetdevice, mpi_comm_rank, mpi_comm_size, mpi_finalize, mpi_init, get_argument, get_dims, run
get_dims calls get_dims_dataloc
run calls apply_BC, define_BC, forcings, mpi_reduce, mpi_wtime, body, handle_io_step, is_restart, update_stats, postprocess, case_finalise, compute_derived_fields, compute_pressure_vert, get_block, has_output_field, is_root, pressure_correction, release_block
case_finalise calls is_root, finalise
compute_derived_fields calls get_block, release_block, compute_qcriterion, compute_vorticity, reorder, tds_solve
compute_pressure_vert calls get_block, interpl_c2v, vecadd
get_block calls create_block, set_shape
pressure_correction calls get_block, release_block, divergence_v2p, gradient_p2v, vecadd
divergence_v2p calls divergence_v2c
finalise calls finalise
gradient_p2v calls gradient_c2v
interpl_c2v calls get_block, release_block, reorder, tds_solve
cleanup_field_arrays calls release_block
divergence_v2c calls get_block, release_block, reorder, tds_solve, vecadd
get_field_data calls get_block, release_block, reorder, copy_f_to_data, get_rdr_from_dirs
get_global_dims calls get_dims_dataloc
gradient_c2v calls get_block, release_block, reorder, tds_solve
prepare_field_buffers calls get_dims, get_global_dims, get_output_dimensions
setup_field_arrays calls get_block, is_root, get_field_data
write_single_field_to_buffer calls get_dims, get_global_dims, get_output_dimensions, stride_data_to_buffer